### ISSUE TITLE
Write docstrings

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#1]
Add numpy docstrings to functions

**Comment by smoia** [comment]
Most of the scripts we have require docstrings, with the exception of those in `heur` folder.
Just to be clear, docstrings are a multiline comment at the beginning of each function that briefly explain what the function is doing, and reports Inputs, Outputs and (after @eurunuela 's comment in #38) outcomes (when the function doesn't have a `return`, but produces something like a file or a print onscreen).
At the moment, `physio_obj.py` has complete docstrings, `phys2bids.py` has complete docstrings with the only exception of method `main()`; `utils.py` has stubs to complete with info on I/O, `viz.py` lacks docstrings.

It's a good first issue to start reading the code and fill in the characteristics of the functions. Python knowledge is not necessarily required.

**Comment by smoia** [comment]
I would still invite someone that would like to start approaching phys2bids code / python3 to complete this issue. Especially in improving `utils.py` docstrings - most of the functions there are quite trivial, and a valid PR doesn't have to cover everything.
Can I suggest @kristinazvolanek , @RayStick or @AyyagariA  for this? 
I can help out remotely! Drop me a mesage somewhere if you're interested.

**Comment by RayStick** [comment]
I am happy to help with docstrings once I have used the code a bit more. Personally, I think it is hard to write docstrings if you haven't written or used the code. So at the very least, we need to use the code, if we are not writing it.

**Comment by eurunuela** [comment]
Given that this issue was labeled as urgent, how are we doing with this?

**Comment by RayStick** [comment]
It seems that @smoia made good progress on this?

**Comment by smoia** [comment]
This should have been closed automatically by #80 . Closing it now.
