### ISSUE TITLE
setup.cfg should be updated to follow the name of the organization

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#102]
There are a couple of lines that reference should reference the physiopy organization instead of a personal GitHub project. See the lines [here](https://github.com/physiopy/phys2bids/blob/8f0bab893280101c8cf6e60fee961737dda62449/setup.cfg#L3).

## Context / Motivation

One would expect to find physiopy references everywhere in the project, which makes it somehow incoherent to find a reference to a personal GitHub project. This change would make the package more coherent with what physiopy is as a community.

## Possible Implementation

It should just be a matter of changing the urls (please correct me if I'm wrong).

**Comment by vinferrer** [comment]
We are actually probably changing the name  because there is a toolbox that has similar name and does similar thing so maybe we should wait

**Comment by eurunuela** [comment]
Absolutely @vinferrer . Opened the issue just to point it out and not forget about it.

**Comment by smoia** [comment]
Closed in commit to master.
