### ISSUE TITLE
New all-contributors issue

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#104]
## Summary

Just a matter of using the all-contributor bot.

## Next Steps

    * 
    * 
    *

**Comment by smoia** [comment]
@all-contributors add @danalclop for design

**Comment by smoia** [comment]
@all-contributors add @AyyagariA for documentation and content

**Comment by smoia** [comment]
@all-contributors add @BrightMG for ideas, content

**Comment by smoia** [comment]
@all-contributors add @CesarCaballeroGaudes for ideas, content

**Comment by smoia** [comment]
@all-contributors add @vinferrer for bugs, code, documentation, review

**Comment by smoia** [comment]
@all-contributors add @soichih for bugs

**Comment by smoia** [comment]
@all-contributors add @rmarkello for bug, code, ideas, infrastructure, review, testing

**Comment by smoia** [comment]
@all-contributors add @smoia for code, ideas, infrastructure, projectManagement, review, documentation, content

**Comment by smoia** [comment]
@all-contributors add @smoia for code, ideas, infrastructure, projectManagement, review, documentation, content

**Comment by smoia** [comment]
@all-contributors add @raystick for bug, documentation, userTesting

**Comment by smoia** [comment]
@all-contributors add @eurunuela for bug, infrastructure, review, testing

**Comment by smoia** [comment]
@all-contributors add @kristinazvolanek for documentation, content

**Comment by eurunuela** [comment]
@all-contributors add @danalclop for design

**Comment by smoia** [comment]
@all-contributors add @kristinazvolanek for documentation, content

**Comment by smoia** [comment]
@all-contributors add @kristinazvolanek for documentation, content

**Comment by smoia** [comment]
@all-contributors add @kristinazvolanek for documentation, content
