### ISSUE TITLE
Adhering to BIDS units standards

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#127]
## Detailed Description

[BIDS uses a standard format for units of measure too](https://bids-specification.readthedocs.io/en/stable/99-appendices/05-units.html).
Our files have different ways to report units, but we should treat them with phys2bids!

## Possible Implementation

A possible implementation is adding a dictionary and a function, either in the main script or in a separate file, that gets called toward the end of the `_main()` function - before exporting the `json` file.
The dictionary contains different possible types of homonyms for the units, and the function reads what units our objects contain and changes them accordingly to the dictionary.

**Comment by rmarkello** [comment]
@smoia: I'm not totally sure I understand what you're asking for here. Could you elaborate a little bit on what you're hoping for? Do you want the code to e.g., convert `mV` to `V` before saving to the JSON file, or are you actually hoping to do more complex unit conversions?

**Comment by smoia** [comment]
I guess it could start with a bit of string substitutions. Let's see if I can clarify this.
BIDS accepts particular unit of measures for each property (e.g. frequencies are measured and expressed in `Hz`, rather than a label saying `1/s`, written in a certain way (e.g. seconds are `s` and not `sec`), with the respective prefixes (e.g. millivolts are a valid unit if written as `mV` and not `milliV`).
As we're trying to respect BIDS indications, I think we should convert every unit of measure into their relative BIDS standard (for instance `sec` to `s`), mainly for the json file.
This could be done by initialising a dictionary of aliases, a bit like it's done [here](https://github.com/all-contributors/all-contributors-bot/blob/7b3df5855b7f52e97baea36731722188a1f3b5da/src/tasks/processIssueComment/utils/parse-comment/index.js)

What do you think about it?

**Comment by rmarkello** [comment]
Gotcha! So steps include:

1. Defining the set of BIDS-compatible units of measurements in some Pythonic format (e.g., a dictionary),
2. Coming up with popular / common aliases for these units that might be used in various physiological data files, and
3. Writing a method for converting data and metadata from arbitrary into the pre-defined BIDS-compatible units before the output files are generated.

(I'm going to remove the "Good First Issue," if that's an accurate summary, because I actually think this is going to be a bit more tricky / time-consuming than expected.)

**Comment by smoia** [comment]
General question relevant to this issue:
Does anyone know how to “multiply” keys between two dictionaries? I mean something like:
```
A={‘a’: ‘c’}
B={‘b’: ‘d’}
operation(A,B) = {‘ab’: ‘cd’}
```
The reason I'm asking is that BIDS supports units of measure and its derivates (like seconds and milliseconds), and being able to operate independently on prefixes and main parts would be better than having to write aliases for each case.

**Comment by rmarkello** [comment]
Hey @smoia: I'm not sure I follow. How do you see that being used in practice?

Implementation-wise, a dict comprehension could work (though it's not the _prettiest_):

```python
>>> A = {'a': 'c'}
>>> B = {'b': 'd'}
>>> C = {a + b: A[a] + B[b] for a, b in zip(A, B)}
>>> print(C)
{'ab': 'cd'}
```

**Comment by smoia** [comment]
Right, sorry - for instance, let's say that a channel was measured in milliseconds.
That's a proper unit standard, that would respect BIDS formatting. However, in the input data that information is stored as `Millisec`, where it should actually be `ms`.
The less verbose path, in my mind, would be to be able to remap that `Milli` into `m` and that `sec` into `s` using a dictionary of aliases. e.g.
```
unit_aliases = {
                    # second: time
                    's': 's', 'second': 's', 'seconds': 's', 'sec': 's',
                    'secs': 's',
                    '1/hz': 's', '1/hertz': 's',
                    # ampere: electric current
                    'a': 'A', 'ampere': 'A', 'amp': 'A', 'amps': 'A',
                    # kelvin: thermodynamic temperature
                    'k': 'K', 'kelvin': 'K', 'kelvins': 'K',
 }
```
 I could have one huge dictionary of all the possible aliases (for seconds, nanoseconds, milliseconds, ...), or I could have one dictionary for prefix aliases (that would remap any "milli" or similar to `m`) and one dictionary for units (that would remap "seconds" and related to `s`). Then find a way to merge them together, as I'm not sure that splitting the input would be an easy task. Is it a bit clearer?

**Comment by rmarkello** [comment]
Much clearer, yes, thank you!

I have to imagine we cannot be the first people with this need! From a quick search, the [`pint`](https://github.com/hgrecco/pint) library seems to be focused on similar issues of arbitrary units + conversions, so it might be worth thinking about using some pre-built solutions rather than trying to roll our own (which, with all the possible units, could get out-of-hand very quickly).

On the one hand, I'm hesitant to add dependencies; on the other hand, `pint` seems quite useful and is a very light dependency (Python + standard library only, ~200kB wheel on PyPi). I'm not tied to it either way, but figured I'd raised the point for continued discussion!

**Comment by vinferrer** [comment]
Hey guys I am gonna try to solve this. However reading the last comments. If you check the code this is already solved for some of the measures in the txt reading functions. Maybe this is not adressed in the acq. @smoia Could you confirm? In any case I see this dictionary thing could be a more proper way to solve it. However do we wanna do this unit changes in the reading or afterwards?

**Comment by vinferrer** [comment]
So at least in the functions of txt.py for the interval and the frequency all units are changed to 's' and to 'Hz' which i think is BIDS compilant

**Comment by smoia** [comment]
Hi @vinferrer. As per assignment, I'm working on this, specifically in [this branch](https://github.com/smoia/phys2bids/tree/enh/bids-units). If you want to jump in, we can work on it together (please PR my branch though), but let's discuss about it first so that I can take you up to speed on it.
The solution I'm going for consists in two dictionaries, one for prefixes and one for units. The idea is that at a certain point (as early as possible, probably after we populate a BlueprintInput), BlueprintInput.units elements are passed to a function that:
  - lowercases the input
  - pass the lowercase input in the dictionary of aliases
  - gets the BIDSified alias

This doesn't come without issues (e.g. the "Mega" prefix and another couple are hard to deal with), but was the best idea I could come up with - not the only one though.
The main problem that I'm facing is how to use the proper dictionary for the proper part, or how to join the two dictionaries together. I was thinking about writing a function that, given two dictionaries as input, creates all the possible combinations of their keys and values. I didn't implement it yet, so if you want, that would be a good place to start.

**Comment by smoia** [comment]
More specifically, it's [this line](https://github.com/smoia/phys2bids/blob/2e9a6e11ad11001546e84b23f723ece43f40a270/phys2bids/phys2bids.py#L191)

**Comment by smoia** [comment]
What is carried out in `interfaces.txt` is different.
This is not about taking everything to seconds or base units of measure, but about being sure that the unit itself is expressed with the right format.
It's also not about doing transformations from unit to unit (not at the moment at least).
It's just to be sure that the right alias is in the right place, _for all the channels_.
