### ISSUE TITLE
Need to know which sampling interval units uses AcqKnowlegde format

### ISSUE THREAD

**Issue by vinferrer** [physiopy/phys2bids#129]
## Summary
I couldn't find a reference of which units can AcqKnowlegde format use for sampling interval 

## Additional detail
For the moment, in txt.py function I am assuming the possible units are ['hr', 'min', 'sec', 'µsec', 'msec']

## Next Steps

    *  Search if there is a reference for sampling interval  units in acq files
    *  Gather actual acq data to test it in different sampling interval units

**Comment by eurunuela** [comment]
I have found this: 

> Set to x/sample: Specify the _inter sample interval_ of data in the file, which will be translated into an appropriate sampling rate. The edit field will accept an arbitrary floating point number. The units menu contains μsec, msec, sec, MHz, kHz, Hz. The edit field will be dynamically converted to match the units selection; no conversion will be used when switching between frequency and time.

See [page 194](https://www.biopac.com/wp-content/uploads/acqknowledge_software_guide.pdf).

**Comment by eurunuela** [comment]
Can we close this issue @vinferrer ?

**Comment by smoia** [comment]
As it might have been addressed and closed by #123

**Comment by vinferrer** [comment]
we can close it
