### ISSUE TITLE
Automatic testing on data with Travis

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#130]
I believe we should have some automatic testing on data with Travis before we release our first non-beta version. This issue is related to #9.

## Context / Motivation

We should always make sure the code works on data, as it is the main purpose of the project. It would definitely make testing the code easier. It could even be helpful for the tutorials in our documentation.

## Possible Implementation

This feature should be implemented in a similar fashion to the unit tests.

**Comment by eurunuela** [comment]
Do you guys think the following tests would be enough for the moment? @smoia @RayStick 

- A test for ACQ (accounting for single and multi-frequency)
- A test for TXT (accounting for single and multi-frequency)

**Comment by RayStick** [comment]
I think those tests would be enough for the moment, yes.
 
What does automatic testing on  data mean, specifically? Would we need to make sure that whatever input we give to Travis, we know what output we _should_ be getting, from a specific data file? At the moment, the data we have in 'test' might need more information about expected output, accessible alongside them, in that case.

**Comment by eurunuela** [comment]
Indeed, that's what we should be aiming for. We should test that, for a given input, the output is what we expect. Of course, how strict we want to be with the output we expect is another thing. I think we should at least cover some minimum (what that minimum is, that's something we have to decide).

**Comment by eurunuela** [comment]
Now that #145 is merged, I believe this tests will considerably increase our coverage. Also, I think #144 should be covered by this issue as I can't think of any better way to test the logger.

**Comment by smoia** [comment]
#144 Might be the only test that is not covered with the integration test, actually - as well as all the `raise/Exception`. I think, however, that with a couple of calls (to test most of the `cli/run.py`) we'll be able to get to our mark (90%) or close enough to feel good about codecov.

As for the tests, we should runa  simple acq and txt singlefreq and multifreq, but also multiple acq (or txt, what's faster) to use most of the options of the `cli/run.py`. @eurunuela , why don't you prepare (or increase) the list of tests you think we should have to cover `cli/run.py`?
