### ISSUE TITLE
[BUG] Exception text not updated with support for txt files.

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#133]
## Expected Behavior

The error message should read:
```
Exception: The file Test_belt_pulse_samefreq.acq wasn't found in tests/data.
phys2bids currently supports: acq, txt
```

## Actual Behavior

The error message reads:
```
Exception: The file Test_belt_pulse_samefreq.acq wasn't found in tests/data or txt is not supported yet.
phys2bids currently supports: acq, txt
```

## Steps to Reproduce the Problem

    1. I gave one of the testing ACQ files as the input and ran the program.

## Specifications

    - Python version: 3.7.6
    - phys2bids version: v1.1.0-beta+222.g96026fc
    - Platform: MacOS

## Possible solution

We must update the exception text.

**Comment by smoia** [comment]
Let's solve this one - anyone interested?

**Comment by eurunuela** [comment]
I believe this issue was solved. I can no longer replicate it.
