### ISSUE TITLE
Add unit tests for txt.py

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#136]
## Detailed Description

Unit tests should be added to #123.

**Comment by smoia** [comment]
@vinferrer, if you want help on the code you can open a draft PR and we can have a look

**Comment by vinferrer** [comment]
actually i was already starting but i don't know if  is better to start a new PR. What do you prefer?

**Comment by vinferrer** [comment]
or add it to the one i already have with txt.py

**Comment by vinferrer** [comment]
One thing, every time I check an if do i need to assert something or if i know the code is running that part should be fine?

**Comment by smoia** [comment]
> actually i was already starting but i don't know if is better to start a new PR. What do you prefer?

@vinferrer, up to you. Let us know what you decide.

> One thing, every time I check an if do i need to assert something or if i know the code is running that part should be fine?

Explain better. Remember that to have better tests (and increase code coverage), you need to test each line of the function. So if you have an `if A else B` statement, you need a test that triggers `A`, and another one that triggers `B`. If you have "cases of" (or the pythonic equivalent) , you need to test each case. If you have a simple `if A` statement, you have to test `A`, but it would be better to test the code without triggering `A`.

**Comment by vinferrer** [comment]
Well I just uploaded the test to the pull request I already had so you can review it, I also added the units for acqknowledge files so you can do the review all together

**Comment by eurunuela** [comment]
@vinferrer could you please reference this issue on #123 ?

**Comment by vinferrer** [comment]
I will actually close it then the PR is finished

**Comment by eurunuela** [comment]
Yes, but reference it please so it can be tracked in the future.

**Comment by smoia** [comment]
Closed by #123
