### ISSUE TITLE
Add unit tests for the logger

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#144]
## Detailed Description

We should add testing for the changes introduced in #134 .

## Possible Implementation

I'd like to know what your opinion is on this matter as I'm still thinking of the best way to write tests fo the logger.

**Comment by smoia** [comment]
We should probably check that the messages are reported - a bit like @vinferrer did in the `test_txt.py` test.

**Comment by eurunuela** [comment]
Sorry, I didn't mean to close the issue. We could check the messages with an independent function in the integration tests.

**Comment by smoia** [comment]
We can check it with a functional test, yes - let's do it like that!

**Comment by eurunuela** [comment]
Already working on it!
