### ISSUE TITLE
Improving trigger pictures.

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#15]
So far, the trigger picture created around [this line](https://github.com/smoia/phys2bids/blob/7dd17dded137fab2653b66812756ed967790dc30/physiobids.py#L409) have a simple title, and show the expected start and expected end of the sequence.
It would be nice to:
- [ ] add the name of the corresponding tsv output file in the title
- [ ] add a third subplot in the second row, that shows the last trigger
- [ ] rescale differently the Y axis in the first row, maybe the higher between twice the max value in the trigger array and three times the threshold?

**Comment by vinferrer** [comment]
I think this is a good first issue but since no one aproach it maybe we should restart it stefano

**Comment by vinferrer** [comment]
@smoia

**Comment by smoia** [comment]
No rush on this, but yes, we can restart it. Wanna take care of it?

**Comment by vinferrer** [comment]
one question. What's the difference between the two plots in the second row?

![image](https://user-images.githubusercontent.com/38909338/75537077-a5765f00-5a16-11ea-97a5-ddc38e9f86d6.png)

**Comment by smoia** [comment]
They should be different - showing the first and the last TR trigger. It's made so that if the sequence is long but you are asking the program to detect beginning and length of the sequence, you can see how the program performed and eventually correct issues.
How did you obtain this output?

**Comment by vinferrer** [comment]
``phys2bids -in Test_belt_pulse_multifreq.txt -chtrig 3`` 
I change the title only everything else comes from the master branch

**Comment by smoia** [comment]
I see. In this case, the fact that the two subplots are the same might arise from the fact that there is no start and length check. We could add a flag, to not draw the second line when this option is not required - or to expand the plot on the left to the whole line.

another thing would be to substitute the time line (orange) with something else - maybe a semi-transparent rectangle on the background?

**Comment by vinferrer** [comment]
Well I am checking the code and the repetition of the plot it's due to the fact that you are plotting the same exact line in both plots:
``subplot = fig.add_subplot(223)
    subplot.set_xlim([-options.tr * 4, options.tr * 4])
    subplot.set_ylim([-0.2, options.thr * 3])
    subplot.secondary_xaxis('top', functions=(time2ntr, ntr2time))
    subplot.plot(time, trigger, '-', time, time, '-')
    subplot = fig.add_subplot(224)
    subplot.set_xlim([options.tr * (options.num_timepoints_expected - 4),
                      options.tr * (options.num_timepoints_expected + 4)])
    subplot.set_ylim([-0.2, options.thr * 3])
    subplot.secondary_xaxis('top', functions=(time2ntr, ntr2time))
    subplot.plot(time, trigger, '-', time, time, '-')``

**Comment by vinferrer** [comment]
I see no difference between the 5 and the last line

**Comment by vinferrer** [comment]
Oh, sry i see the xlim now

**Comment by vinferrer** [comment]
Yeah so basically ``options.num_timepoints_expected`` is zero in this case

**Comment by vinferrer** [comment]
So I have changed the function a bit and now this is the output with the file:
![image](https://user-images.githubusercontent.com/38909338/75545468-a7e0b500-5a26-11ea-8d9b-75463431d8d8.png)

**Comment by vinferrer** [comment]
I can share the new code by PR but maybe we should discuss the third plot. Why do you wanna plot the last trigger only? this can be seen in the second figure

**Comment by vinferrer** [comment]
![image](https://user-images.githubusercontent.com/38909338/75554054-e2078200-5a39-11ea-8753-03703ac99ce7.png)

**Comment by vinferrer** [comment]
state of the plot at this moment
