### ISSUE TITLE
OSError on windows 10

### ISSUE THREAD

**Issue by sangfrois** [physiopy/phys2bids#171]
**When trying to run the [test illustrated in the docs](https://phys2bids.readthedocs.io/en/latest/howto.html) from a windows environment, I get an OS error. Even though the package is at an early stage, I wanted to mention it because the problem seems simple to solve.**

## Expected Behavior
When in directory `phys2bids/tests/data`, and running the command `phys2bids -in Test_multiscan100Hz_trig_samefreq_header.txt -info`, you would expect a nice output like the one in the docs.

## Actual Behavior
Instead of the beautiful output, I get that 
![image](https://user-images.githubusercontent.com/38385719/76452758-03f0f500-63a8-11ea-8b72-eb13774b8c18.png)

From my understanding, it seems like the *Logging* package that is used to produce the output file name doesn't spit a proper path. On Windows, the directory looks somewhat like this `C:\Users\etc\etc`. 

Python usually converts these windows path to either a string format like this : `'C:\Users\etc\etc'` 

or a double back-slash format like this : `C:\\Users\\etc\\etc`

In my case, it seems like it does both, so it's considered an invalid argument : `'C:\\Users\\etc\\etc'`

**Everything runs smoothly on a Linux/Ubuntu 18.04LTS system**

## Steps to Reproduce the Problem

1.  Go on a `windows/latest` system
2.  Have your python env installed with phys2bids (On my machine, **GitBash** is installed using**Linux Subsystem for Windows**. and my Conda environment is specified in $PATH. it doesn't look like the usual windows command line interface).
3. Open Anaconda prompt, or a Command Line application fed with your conda path.
4. Reproduce steps given in the [docs](https://phys2bids.readthedocs.io/en/latest/howto.html)

## Specifications

    - Python version: 3.7
    - phys2bids version: dev version, `phys2bids 1.3.0b0+111.g20fc77e`
    - Platform: 2020-03 Cumulative Update for Windows 10 Version 1809 for x64-based Systems (KB4538461)

## Possible solution
So, I'm not a expert, but it seems like the problem lies in the way the output path is formatted here (Line 211, `phys2bids.py` : 

   ``` # Set up logging file and open it for writing
    log_handler = logging.FileHandler(logname)
    log_handler.setFormatter(log_formatter)
    sh = logging.StreamHandler() 
```

**I've test all functions and it systematically gives this error. I suggest that in further versions, we include a conditional statement for windows path format** (i.e. if windows users want to format their phys files in BIDS).  I will post my attempts to solve this issue here

**Comment by smoia** [comment]
Thanks for pointing this out @sangfrois!
Unluckily we can't cover Windows support for the moment, as none of the current contributors uses it.
We are going to look into this soon though!

**Comment by eurunuela** [comment]
That's right, right now we're covering Linux and MacOS. However, if you feel comfortable with the whole GitHub and Python thing, and would like to contribute, feel free to fork the project, open a branch and write a fix! We're more than happy to have [contributors](https://phys2bids.readthedocs.io/en/latest/contributorfile.html)!

**Comment by rmarkello** [comment]
Hi @sangfrois ! Thanks so much for this thorough issue 🙌 

I think the root of this problem is that **Windows systems don't support colons in filenames**. Because the logger file has colons in the timestamp at the end of the filename Windows systems won't ever be able to generate them (colons are one of the few "protected" characters on Windows), so we'll always receive that error. The solution should (hopefully) be as straightforward as changing the colons in the logger filename to either hyphens or underscores or something that is more cross-system compatible!

(This is also a good impetus / reminder that we need to try and get some Windows testing support using an automated solution like [AppVeyor](https://www.appveyor.com/)!)

**Comment by eurunuela** [comment]
@sangfrois could you test with #176?
