### ISSUE TITLE
Add Windows CI testing

### ISSUE THREAD

**Issue by rmarkello** [physiopy/phys2bids#174]
We are currently not testing (nor developing) `phys2bids` on Windows systems, leading to issues like e.g., #171. I think we should look into adding Windows CI testing using a service like [AppVeyor](https://www.appveyor.com/) or [Azure Pipelines](https://azure.microsoft.com/en-us/services/devops/pipelines/) (since TravisCI currently only has [minimal](https://docs.travis-ci.com/user/reference/windows/) Windows support).

## Context / Motivation
We shouldn't limit our users to those researchers working on Mac or Linux systems, so adding AppVeyor or Azure support / testing so that we can ensure our primary workflows are viable on Windows is critical.

## Possible Implementation
`nipy/nibabel` recently moved to Azure Pipelines from AppVeyor (relevant files: [1](https://github.com/nipy/nibabel/blob/master/.azure-pipelines/windows.yml) [2](https://github.com/nipy/nibabel/blob/master/azure-pipelines.yml)); we could look into simply copying the relevant portions of their framework for `phys2bids`.

**Comment by smoia** [comment]
I think it's a great idea, let's do it! Azure Pipelines is already installed in all the physiopy repos, lee me know if there is any problem in setting it up!
Thank you for taking care of it!

**Comment by smoia** [comment]
@rmarkello, any update on this?
I'm asking because if it didn't get to development yet and you don't mind, we could add this to the list of BrainWeb issues!

**Comment by rmarkello** [comment]
Sorry! This has been on my list but I have not yet had a chance to get around to it. I did set this up on one of my own repos a few weeks ago and it was a bit more of a pain than I expected it would be. That said, if someone else wants to address it ASAP then I'm happy to advise. Otherwise I'll try and get around to it in the next ~week or two.

**Comment by smoia** [comment]
No rush - take your time! I'll leave this issue out of the BrainWeb
