### ISSUE TITLE
Discussion on the ordering of library imports

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#182]
## Summary

Each one of us has got a different way of ordering the library imports and I believe we should have some guidelines to follow. The idea is that we are all on the same page. Also, this should make reading and reviewing the code easier on the eye.

The following is a possible guideline:
1. Standard library imports
2. Third-party library imports
3. Internal library imports

where each set of imports is in alphabetical order, ideally separated by a blank line.

If you agree on making the suggested guideline the default, please upvote. If you have a better suggestion, please comment on this issue. I will keep this issue open for a week and will open a PR that updates the imports with whatever guideline has got the most upvotes once the issue is closed.

Tagging the most active members in the project: @smoia, @vinferrer, @rmarkello, @RayStick.

## Next Steps

- Open a PR that updates the imports following the outcome of this discussion.

**Comment by smoia** [comment]
Totally agree! This would follow better [PEP8 conventions](https://www.python.org/dev/peps/pep-0008/#imports).
What would you (all) prefer as order:
```
import matplotlib.pyplot as plt
import scipy.signal
from numpy import array
```
or
```
import matplotlib.pyplot as plt
from numpy import array
import scipy.signal
```
?

PEP8 doesn't specify this case.

**Comment by eurunuela** [comment]
I like the first proposal better.

May I ask you to only upvote the guideline you would like to be implemented? This means you should remove the upvote from the first proposal if you'd like to vote for another one.

**Comment by smoia** [comment]
Ok, let's try again,

It seems that we agree to follow  [PEP8 conventions](https://www.python.org/dev/peps/pep-0008/#imports).

Is the difference you see between just following alphabetical order (case 2) vs import/from distinctions (case 1)?

**Comment by eurunuela** [comment]
Oh, I follow you. 

I'd rather have _import_ first, then _from_.

**Comment by smoia** [comment]
Then, final vote:
@eurunuela @rmarkello @RayStick @vinferrer and *all the others that want to express a preference*, **knowing that we will follow PEP8 standards as proposed by @eurunuela**, vote with a:
:tada: for **case 1** (*import* first and *from* second, but alphabetical within them):
```
import os
import sys

import matplotlib.pyplot as plt
import scipy.signal
from numpy import array
from pandas import Series

import phys2bids.viz
from phys2bids import utils
```
or :rocket: for **case 2** (strict alphabetical order):
```
import os
import sys

import matplotlib.pyplot as plt
from numpy import array
from pandas import Series
import scipy.signal

from phys2bids import utils
import phys2bids.viz
```

**Comment by vinferrer** [comment]
after voting, should we make a bit PR to change the order in all the files?

**Comment by eurunuela** [comment]
Don't worry @vinferrer, I'll take care of it. Just make sure that whatever you're working in right now follows the new guidelines before merging!

**Comment by vinferrer** [comment]
sure
