### ISSUE TITLE
Output files are not BIDS compliant

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#184]
## Expected Behavior

Following [BIDS 1.2.2](https://bids-specification.readthedocs.io/en/v1.2.2/), the `.tsv.gz` files should have a column for each channel.

## Actual Behavior

Our output has a row for each channel

## Possible solution

We can solve this in two ways:
1. a very easy very quick `BlueprintOutput.timeseries` transpose before (during) the final export to `tsv`, or
2. a less easy, less quick inversion of `BlueprintOutput.timeseries` indexes, followed by adaptation of the scripts, so that `BlueprintOutput.timeseries` will be always created and managed as if we were importing a BIDS compliant `tsv` file.

I prefer option number 2, that could be a bit less easy, but will work very well in case we need to import files or we need this object to be used in other libraries that only import BIDS compliant files. But I'd like to know what y'all think (starting with code contributors @vinferrer @rmarkello @eurunuela)

(thanks to @sangfrois for pointing it out)

**Comment by rmarkello** [comment]
Totally agree that the output should be made BIDS-compliant&mdash;that's literally the whole point of `phys2bids`! 

I think I agree in-principle that the second solution is the ideal approach, but for the moment (while we figure out the logistics of that), can we quickly implement the first solutiuon just so people using the tool are getting BIDS-compliant files?

**Comment by eurunuela** [comment]
Totally agree with @rmarkello . Making the package “usable” (BIDS-compliant) should be the priority right now.
