### ISSUE TITLE
Check that phys2bids is BIDS 1.3.0 compliant.

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#185]
## Detailed Description

At the moment, the latest stable BIDS is `v.1.3.0`.
BIDS has detailed specifications on many things, starting with how the files should be named, how they should be organised internally (see #184), how  information should be reported (see #127).
I'm not totally sure that `phys2bids` complies to that specification - although we definitely have to!

## Possible Implementation

1. Read BIDS 1.3.0, especially the section relative to physiological files, functional MRI files, units of measure.
2. Check that our output is compliant to that specification
3. If not, open bug issues to have it fixed
4. Add in the documentation and in the `readme` that we are bids 1.3.0 compliant (a sentence? a nice badge?)

**Comment by smoia** [comment]
@RayStick @rmarkello , do you think this could be a good first issue?

**Comment by smoia** [comment]
@vinferrer at what point is this issue? Do you need any help?

**Comment by vinferrer** [comment]
I didn't had time to go through it. Help is always welcome, specially since i am no expert in BIDS and I am bad at details. Which is important for standards

**Comment by vinferrer** [comment]
In theory #222 should close the units of measure part. Although ``mmHg`` is a cranky issue since is not bids standard but is necessary in some channels.

**Comment by vinferrer** [comment]
I don't understand in which way specifically functional MRI files standard affects us. I suppose it is in an indirect manner

**Comment by vinferrer** [comment]
I tried the tutorial file with the heuristic and the names and structure seem to check with bids standard

**Comment by vinferrer** [comment]
However in this case there is not stimuli file, don't think we have those

**Comment by vinferrer** [comment]
Lastly, regarding the JSON file, all seems good to me. However, I was wondering what happens with the sampling frequency when you have multifrequency files. Does that generate different ``tsv and JSON`` files for each frequency?

**Comment by smoia** [comment]
> Lastly, regarding the JSON file, all seems good to me. However, I was wondering what happens with the sampling frequency when you have multifrequency files. Does that generate different `tsv and JSON` files for each frequency?

Indeed, as it's the expected output to have  BIDS compliant physiological files (from what I understood from the BIDS specs).

> However in this case there is not stimuli file, don't think we have those

We don't for the moment. I don't know if we want to support Respiract files, in which case we might have stimuli files? @RayStick @BrightMG what do you think about this?

> I don't understand in which way specifically functional MRI files standard affects us. I suppose it is in an indirect manner

They affect the physiological files since the name of the files should be deriving from the fMRI (/EEG/MEG?) file relative to the same scan. In fact, once #219 is in place, it would be nice to see if we can automate this process in general and get the filenames from BIDS structures (rather than from heuristics or yamls).

Thank you @vinferrer for the check. I think that, once you are positive about how things work, we can close this issue with a PR that specifies in the main readme and in the documentation first page ([`index.rst`](https://github.com/physiopy/phys2bids/blob/master/docs/index.rst)) that we are 1.3.0 compliant!

**Comment by vinferrer** [comment]
Should we update this issue?https://bids-specification.readthedocs.io/en/stable/

**Comment by vinferrer** [comment]
Or we go for BIDS 1.3 compilant and then open one for 1.4?

**Comment by smoia** [comment]
Let's see if we can get the _help from the public_:
@effigies, we prepared this software to be BIDS 1.3.0 compliant. We saw today that BIDS is now at version 1.4.0.
Since we don't have derivatives as outputs (`phys2bids` prepares only the raw data), do you think we're also 1.4.0 compatible, or are there more differences between the two BIDS versions?

**Comment by smoia** [comment]
Looking at the [changelog](https://github.com/bids-standard/bids-specification/releases/tag/v1.4.0), we should be fine, but I think there is a BIDS validator [somewhere](https://bids-standard.github.io/bids-validator/). @vinferrer, could you check if our outputs pass the validator? If so, we should be good to go.

**Comment by effigies** [comment]
We aim for backwards compatibility with the spec, so anything that was valid should still be. (If you had something unspecified, then it could now be specified otherwise, though.) I think you're probably safe, but I would check the changelog to be sure.

**Comment by smoia** [comment]
@effigies cool, thank you!
Is there a nice badge the BIDS team has to specify the compatibility?

**Comment by robertoostenveld** [comment]
some files that I see are missing

```
dataset_description.json
participants.tsv
participants.json (optional)
README
CHANGES (optional)
```

**Comment by vinferrer** [comment]
Tutorial output folder: https://drive.google.com/drive/folders/1ZtpONACc443iqasCzmqwDmx3eilcFI8j?usp=sharing

**Comment by robertoostenveld** [comment]
I am not sure whether `.tsv.gz` is allowed. 
the `.log` file is not part of BIDS (afaik)

**Comment by vinferrer** [comment]
Thanks Robert, I was able to review the bids struct to see if we can tackle the basic stuff so we are bids compatible ( in a minimum way) and then build from there. If I am correct the compulsory files that we lack are:

```
dataset_description.json
Fields
Name (Required)
BIDSVersion (Required)
DatasetType (Recommended)
License (Recommended)
``` 
```
Participants.tsv
Fields
participant_id (Required)
age (Recommended)
sex (Recommended)
handedness (Recommended)
``` 
```
README
```
So I am gonna create an issue for this where we tackle these basic errors

**Comment by vinferrer** [comment]
> I am not sure whether `.tsv.gz` is allowed.
> the `.log` file is not part of BIDS (afaik)

Actually, in physiolical recording files `tsv.gz` is the standard, but for sure we will move away the .log file

**Comment by smoia** [comment]
I believe this is closed now?
