### ISSUE TITLE
Tutorial documentation on trigger picture and ntp outdated

### ISSUE THREAD

**Issue by vinferrer** [physiopy/phys2bids#190]
## Summary
The howto.srt tutorial is now outdated after #183, we should rewrite it and improve it

## Next Steps

    * Add detailed description about the automatic ntp method
    * explain how to use -thr now
    * Maybe we need a file where the new method does not work, we can modify the tutorial file, make one of the triggers smaller

**Comment by smoia** [comment]
@vinferrer , why don't you open a Draft PR with the commit you made to #183 containing modifications to the `howto.rst`?
Then @RayStick and I can help you with the tutorial rewriting!

**Comment by vinferrer** [comment]
We should address quickly #188 before this, don't you think?

**Comment by smoia** [comment]
It's two different PRs so they can both be open, but yes, working on #188 is also important! Start wherever you prefer!
