### ISSUE TITLE
phys2bids April developer call (09.04.2020 @ 9AM CDT/10AM EST/16.00 CEST)

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#194]
Next developer call: 9th of April 2020.
It will take place over Skype, and the call can be joined [here](https://join.skype.com/Rm4B7R30TG6g)

Find the agenda [here](https://docs.google.com/document/d/1lezQneuwPlvGxKo4qC1IgaVg5KEnHKdj1iEQ7qDoFjI/edit?usp=sharing)

And the doodle to set the time [here](https://doodle.com/poll/xisvee6h5rye2c7e)

Old minutes [here](https://drive.google.com/open?id=1zfc-hgRcU1k2XdqKD8v6TGwQX_jeCUea)

**Comment by marcelzwiers** [comment]
Hi There, I would be very interested in joining your developer call and discuss possible integration. Can you recommend some docs or so as a quick-start for me to get an overview on the working/design of phys2bids? For you you can have a look at my doc-page (https://bidscoin.readthedocs.io) or, perhaps better, watch the demo:
https://youtu.be/aRDK4Gj5qzE?t=819

**Comment by smoia** [comment]
@marcelzwiers , I would say that reading our documentation would be the best way to approach `phys2bids`, starting from the [tutorial](https://phys2bids.readthedocs.io/en/latest/howto.html) and following with the [heuristic file](https://phys2bids.readthedocs.io/en/latest/heuristic.html) and the [contributors guide](https://phys2bids.readthedocs.io/en/latest/contributorfile.html). I'm afraid our API documentation is not ready yet.
Thank you for your documentation, I'll for sure go through it, maybe also @rmarkello and @eurunuela could give it a read?

Are you going to participate in the [brainweb kickoff and hackathon](https://brain-web.github.io/#events)? We could work on this integration there.

**Comment by smoia** [comment]
Next call will take place on the 9th of April, at 9AM CDT/10AM EST/16.00 CEST

**Comment by smoia** [comment]
Taking place in this moment!
https://join.skype.com/Rm4B7R30TG6g

**Comment by smoia** [comment]
Minutes at the same link of the agenda.
