### ISSUE TITLE
Join the Brain Web with a phys2bids dedicated project

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#201]
I'm sorry for the late decision and short time to discuss about it (and especially the fact that this time is a weekend).
I know it's a last minute decision, but from April 6th to April 9th a [Brain Web hackathon](https://brain-web.github.io/#events) will take place.
It could be a great moment to work a bit on some developments for `phys2bids`, and to reach new collaborators! There is some things left to do before June, and exciting new features we can add with the help of experts in fields we don't cover ourselves - e.g. an _automatic detection of the content of the channels_ that would probably require a machine learning approach. 
I would love if we could join the event, and I will set up the repository to help new collaborators join for the occasion. I will also try to follow the development as much as I can, but if any other volunteer could help in the supervision of these three days development, it would be great.
What do you think about it? Are you supportive of the idea?
If so, I will open a project and/or a milestone to track the advancement of phys2bids development in these three days.
I will also add a label, `BrainWeb` to those issues that could benefit from this development. If you have any open issue or any new feature to propose that you'd like to see developed, please let me know in this issue!
@rmarkello @eurunuela @vinferrer @BrightMG @RayStick @CesarCaballeroGaudes and all the others, I'd like to hear from you!

## Outstanding questions
- Shall we join the `BrainWeb`?
- Any volunteer to help me in the supervision of the development?
- Any open issue or new features that you'd like to see developed?

**Comment by eurunuela** [comment]
I think it's a great opportunity for `physiopy` to get new collaborators. 

I was thinking of taking part in the event anyway, so developing for `phys2bids` would be a win-win scenario.

It could be a great opportunity to work on #199. However, we should probably address #186 first, before we integrate `phys2bids` with `BIDScoin`.

**Comment by sangfrois** [comment]
What a great last minute idea! Really, I think the delay is just fine. I don't feel like there's any weekends anymore.

Of course, i'd like to see #36 concretized more and more. I've been taking notes and figuring out how to put the pieces together for a couple of days now. I think it would be the perfect moment to dive into it and implement something. Would you have a little time to spare for me during this event, @smoia ? I would be happy if you could chat with me and ascertain if my understanding is correct.

Any ways, you can count me in for this coding blitz!!

**Comment by smoia** [comment]
@sangfrois , I was thinking the same! We can work on it together and see where it gets us!
Should we label it for BrainWeb?

**Comment by sangfrois** [comment]
Yes cool, let's do this :)

**Comment by vinferrer** [comment]
seems an interesting conference. I have registered and I will try to follow it and colaborate
