### ISSUE TITLE
Add documentation page on "What's BIDS and why adopting it"

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#202]
## Detailed Description

Our documentation lacks a short, BIDS-oriented section in which we give the principles of BIDS and we explain what's the advantage in adopting it.
Writing it would be very useful - and finally close #12!
It doesn't have to be extended, something around half an A4 page could be more than enough.

## Possible Implementation

There are many resources we can use to write a couple of paragraphs, starting from [BIDS' website](https://bids.neuroimaging.io/), its [further information paragraph](https://bids.neuroimaging.io/index.html#further-information) and its [Nature Scientific Data paper](https://www.nature.com/articles/sdata201644).
There is also the first part of this [video](https://youtu.be/aRDK4Gj5qzE?t=13) that could be used.

**Comment by smoia** [comment]
@RayStick @rmarkello , do you think this could be a good first issue?

**Comment by RayStick** [comment]
Yes, I think if the person is familiar with BIDS and/or looks into those resources, I think it could work as a good first issue. But see what @rmarkello thinks, as well. :)
