### ISSUE TITLE
Suggestion for installation instructions and phys2bids tutorial

### ISSUE THREAD

**Issue by kristinazvolanek** [physiopy/phys2bids#210]
##  Summary
After working through the phys2bids tutorial:
A suggestion for the installation instructions in installation.srt document.
A suggestion for the howto.srt document.

## Next Steps

    * In installation instructions: clarify what the difference is between installing as a package and cloning from the git repo. Make a clearer distinction in the installation steps for these two options. (e.g. if you use "pip3 install phys2bids" is that all you need to do before checking the version and using phys2bids?)
    * In phys2bids tutorial: add summary list of all options that can be used after the phys2bids command and what their purpose is (basically, a more detailed version of the help text). For simplicity, instructions on how to use the -h option could be added.

**Comment by smoia** [comment]
@kristinazvolanek, do you want to give it a shot and make the PR yourself?

Spoiler alert: there is already the list of all the arguments [here](https://phys2bids.readthedocs.io/en/latest/cli.html) - it's the help print. Do you think it's worthy to add it to the tutorial too? We could definitely add a link to that page though.

If you think the help page should be more detailed, we can definitely expand it!

**Comment by smoia** [comment]
For the Good First Issue, I thin that the steps necessary to submit a PR would be:
1. Read the two pages
2. Read how to clone a repository and how to use pip(3)
3. Read how to install a local package or a remote package, and how to install a package as a developer.
4. Change the `installation.rst` page adding as much text as needed to explain the different suggested in the "Next Steps"
5. Add a `phys2bids -h` explanation in the tutorial, as well as whatever is necessary to explain better the arguments (either a link to the right page, or a detailed list).
