### ISSUE TITLE
Azure tests pass while the actual test code raises an error

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#215]
## Expected Behavior

Azure tests should fail when pytest raises an error.

## Actual Behavior

As discussed in #206, the Azure tests pass even if the pytest code raises an error.

## Possible solution

As @rmarkello said in #206 : 

> I think adding `failOnStderr: true` to the "Run tests" script in the `.azure-pipelines/windows.yml` definition file should catch this.

**Comment by rmarkello** [comment]
I'm taking a look at this (finally) and from what I can tell in the docs the `failOnStderr: true` is supposed to be the default for Azure Pipelines, and I'm genuinely not sure why things started working again! I can add it just in case, but I'm not sure if that's really the solution... Will open a PR and see what happens 🤷‍♂️
