### ISSUE TITLE
phys2bids May developer call (14.05.2020 @ 12PM CDT/ 1PM EDT/ 19.00 CEST)

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#218]
Next developer call: 14th of May 2020.
Contrarily to what we've been used to until now, the next call will take place over **jitsi, not over Skype**, and the call can be joined [here](https://meet.jit.si/phys2bids).
Jitsi doesn't require to install any additional software but a web browser, if you want to connect by desktop (it will require to install the app to be used on handheld devices).

Find the agenda [here](https://docs.google.com/document/d/1anqlS6cOnjsIHWZc81bDi4HARNaT98nPxFqvnj1elRI/edit?usp=sharing) and don't be scared to add/suggest/press for topics! 

The doodle to set the time is [here](https://doodle.com/poll/tpg3kcc6e4cf93ev). Since this is the last dev call before the end of the milestone, there will be more options than the usual ones to maximise participation.
As usual, you have time until Saturday at 12 CEST to fill it in!

Old minutes are [here](https://drive.google.com/open?id=1zfc-hgRcU1k2XdqKD8v6TGwQX_jeCUea)

**Comment by smoia** [comment]
Next phys2bids meeting on Thursday 14th of May, at 12PM CDT/ 1PM EDT/ 19.00 CEST, on [jitsi:](https://meet.jit.si/phys2bids)

**Comment by RayStick** [comment]
Apologies that I can’t join this call tomorrow, my to-do-list is too big. I will try to finish the issues I am assigned to very soon (particularly if they relate to the milestone). I am happy to be assigned to review PRs, leading up to this milestone.

**Comment by vinferrer** [comment]
Closing this

**Comment by smoia** [comment]
Updated minutes [here](https://docs.google.com/document/d/1anqlS6cOnjsIHWZc81bDi4HARNaT98nPxFqvnj1elRI/edit?usp=sharing)
