### ISSUE TITLE
CI tests failing due to bad data download

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#221]
## Summary

It seems that since a couple of days, both Azure and Travis are failing some or all the jobs due to a "bad" retrieval of the testing data.

The typical error is either:
```
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 17361695 out of 17378311 bytes>

urlopen error retrieval incomplete: got only 17373909 out of 17378311 bytes
```
or 
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
```

All those issues started more or less after OSF latest [system maintenance](https://status.cos.io/), but I can't figure out why they happen.

The only reason I can think about could be that we're opening too many connections to OSF to retrieve the data.
In that case, we can do one or more of the following:
  - Momentarily turn off Azure. It's not the best solution, but since it's not working properly anyway (see #215), that may let Travis do its job and at least we would have one testing suite working. 
  - [Cache the tests files in Travis](https://docs.travis-ci.com/user/caching/#arbitrary-directories). This won't speed things up, but maybe it will help. I don't know if we can do it in Azure.
  - Change host site for the files. For instance, we can open a google account for physiopy and put some test files in drive.
  - Configure the tests to retrieve files only after a certain time passed since the last retrieval. This will slow down the tests though.
  - ...

Any suggestion?

I read that using request instead of urllib could also be a possibility, I wonder if it would solve the issue.

**In the meatime, if you're reviewing a PR, please check it out and test it locally,** running flake8, pytest, and sphinx.

## Additional detail

Check any recent Travis or Azure log

## Next Steps

 - Figure out where the issue comes from.
 - Figure out what to do.

**Comment by eurunuela** [comment]
I can help with this @smoia!

**Comment by vinferrer** [comment]
If you want an example of a acq shortened file to reduce test time, this one should do:
https://osf.io/4yudk/

**Comment by smoia** [comment]
Following our call, we can "craft" a short version of files that we have now and put them in the "test_data" folder in OSF.
I would just like to be sure what would change when we manually cut txt files coming from Labchart. @RayStick, would you be able to create a shorter version of a file that we have in OSF (45-60s, two "real" channels), so that we can see the differences and then operate on the other files we need? If there is a file like that already, you can just point it out!

Another thing that we could do is to decide what is the bare minimum we really need for the tests.
For most of the tests we don't need more than two channels, and probably not more than 100 samples (provided that we have at least two triggers in them). For the integration tests, the `Test_belt_pulse_multifreq.acq` in the folder "donostia" could be used instead of the current one (acq files are much more lightweight than any txt).

**Comment by RayStick** [comment]
I can do make that data file today. I can base it off "Test3_BHscan" that is currently in OSF, which has 534 vols and 4 real channels. 

**I could make it:**
- Two channels (trigger and CO2?)
- Header information
- Less than 60 seconds of data exported

Preferences on whether you want time column included or not? I could export it both ways - with and without the time column if that helps.

**Comment by RayStick** [comment]
I've added some files to "test_data" in OSF. Let me know if you need more.

**Comment by eurunuela** [comment]
I believe the biggest issue is `test_txt.py` and we should focus on it mainly. The txt test is the one with the largest amount of functions and data downloads (I've counted 4). What's more, txt files are bigger than acq files.

@RayStick , @vinferrer  would it be possible to trim the following files?

- `Test_2minRest_trig_multifreq_header_comment.txt`
- `Test_belt_pulse_samefreq_no_header.txt`
- `Test2_trigger_CO2_O2_pulse_1000Hz_534TRs_no_time.txt`

I believe the other file has already been trimmed: `Test_belt_pulse_samefreq_short.txt`

We should also move those new trimmed files into the `test_data` directory in OSF.

**Comment by RayStick** [comment]
I don't think I can see _Test2_trigger_CO2_O2_pulse_1000Hz_534TRs_no_time.txt_ - where is that?

I don't think I uploaded _Test_2minRest_trig_multifreq_header_comment.txt_- I think was someone else in the lab, so it's not immediately obvious to me where that is from. If it's important, I can try to check with the others in the lab.

**Comment by eurunuela** [comment]
Maybe @vinferrer uploaded those files?

**Comment by smoia** [comment]
I'm positive that @vinferrer added the one with the comment.
In any case, how far are we from closing this issue?

**Comment by eurunuela** [comment]
I was hoping someone who has already worked with the files would trim them as I've never worked with these. I'll do them anyway. Hopefully before next weeks meeting.

**Comment by RayStick** [comment]
If you like, let me see what I can work out by the end of today @eurunuela. Even if they were not my files I can probably still trim them easily.

**Comment by eurunuela** [comment]
Thank you @RayStick I'd really appreciate that. I can update the tests to retrieve the new trimmed datasets. The list of files we're currently using is a couple of comments above. Please let me know.

**Comment by smoia** [comment]
In fact, I was wrong. the almighty OSF reveals that the files were uploaded by @AyyagariA .

@RayStick , if you're already tweaking with the files, may I ask you to also reduce the frequency of the files, and in particular of [this four scans file](https://osf.io/k98b5/)?

**Comment by RayStick** [comment]
What frequency would be best @smoia?

**Comment by RayStick** [comment]
Ok just to be clear - 

Shall I cut these files to 1 min in length and 100Hz sampling frequency? (At the moment they are 1000Hz)

**Comment by smoia** [comment]
The idea is this: We're using the files to test some particular features. Depending on the feature and on the test, files can be as short as we like and as low frequency as it lets us have a trigger channel that makes sense.

I would say 100Hz should be more than enough to have a decent trigger channel that has trigger pulses composed by more than one sampling.
Ideally the files should have some padding that is longer than the TR at the beginning, between the others to test that the multi-frequency check that @vinferrer wrote works (especially the multi-frequency file).
I think trigger + one or two other channels should be enough for most files.
The multi-frequency file should have trigger + three channels, one with the same frequency as the trigger, one with higher and one with lower frequency.
The multi-runs could have trigger + two channels, one of which with different frequency, with the lowest sampling possible to still get a decent trigger channel but to be lightweight.

This said, since @eurunuela is working on this, he knows better what we need in this moment, so please @eurunuela check that it makes sense.

**Comment by RayStick** [comment]
Ok, thanks for the information. But I will also wait to check what @eurunuela says. Therefore, these files may only get made tomorrow. (Also, I can't do this really quickly). 

Do we know how many triggers (-ntp) are left in these cut files?

**Comment by smoia** [comment]
Yes, I guess we'll have to rewrite the .json that comes with the files to know triggers and other things.

**Comment by RayStick** [comment]
As this is urgent, I will do this tomorrow morning (central time, 9-10.30am) once hearing back from @eurunuela (who is probably asleep right now). It will be good to double check what is needed before starting.

**Comment by eurunuela** [comment]
Indeed, I was asleep. I think what @smoia suggests makes sense. Below 60 seconds would be great too.

Just to make it clear, right now we're using the following files:

- Same frequency regular file (already trimmed).
- Same frequency with no header (needs to be trimmed).
- Same frequency with no time (needs to be trimmed).
- Multi frequency (needs to be trimmed).

**Comment by RayStick** [comment]
Okay, I have uploaded the adapted files for one of the recordings:
_Test2_trigger_CO2_O2_pulse_1000Hz_534TRs_no_time.txt_
The prefix is now _Test2_samefreq_onescan_ because the orig filename does not make sense anymore  - all the details about the new files can be found in the json files. 

I will look at the others files that need adapting now.

**Comment by eurunuela** [comment]
Thank you so so much @RayStick !! 🥇

**Comment by RayStick** [comment]
No problem! 

Uploaded _**test_data/Test_belt_pulse_samefreq_short no_header.txt**_
However, I was not able to open the original acq file (as I did not upload it), so all I did was open up Test_belt_pulse_samefreq_short.txt and delete the lines with header information. If we need json files for this (or any other exports) one of the donostia team will have to do that :)

**Comment by RayStick** [comment]
Okay, for a **multi-run recording** I have exported files into test_data with this prefix **Test2_samefreq_TWOscans**. I did not have a multi-run recording with different frequencies so I just exported 2 channels, at the frequency of 100Hz, to keep the file size to a minimum. Also, I only exported 2 scans (not _four_scans_, as we previously had). 
This is because:
(1) this should be enough to test a multi-run code whilst keeping the file size down 
(2) the third scan in the original four_scans files was actually an ASL scan, which has triggers with uneven spacing, and could cause issues with these initial tests. 

@smoia if you still want the original four_scans exported at 100Hz, or with more channels, I can do that.

**Comment by RayStick** [comment]
So I think that just leaves **_Test_2minRest_trig_multifreq_header_comment.txt_** from the ones requested. This file is confusing me a bit (even though each channel may be recorded at a different freq, I am not sure if that manifests in the _exported_  frequency) so I will have to return to it later.

**Comment by eurunuela** [comment]
Wow, thanks @RayStick ! I think this is more than enough to start updating the tests. I expect the tests to be faster even if not every file is trimmed.

I'll start pushing commits to #226 and I'll add you as co-author. Thanks again!! 😊

**Comment by RayStick** [comment]
Okay, great. 

I've stopped working on the multi_freq file for today but if it seems that we still need/want that file changed as well, I could take another look next week.

**Comment by eurunuela** [comment]
It would be great if you could take a look at it yes. I'm doing some local checks and the multi_freq tests take the longest. Probably because `phys2bids` makes many checks on multi_freq files.

**Comment by RayStick** [comment]
Great!  🙌🏻

I will see if I can another look a look at the multifreq file later today (but that'll be more like 4pm central time).

**Comment by eurunuela** [comment]
Sure, no problem! I think it would be really cool to have it for our next meeting, so no rush 😉

**Comment by eurunuela** [comment]
So, without updating the multi-freq files, which I believe will have the biggest impact, Travis already takes 40 seconds less to do the whole testing. You can check in #226 .

However, I can see no impact on the azure tests. It seems like azure tests take longer by default (8 minutes vs 4 minutes on Travis). I'd wait until we have the multi-freq file trimmed down to make conclusions.

**Comment by RayStick** [comment]
I'll upload a few new versions of the multi-freq files in a couple of hours time, and we can see how much of an impact that makes.

**Comment by eurunuela** [comment]
Thanks @RayStick!

**Comment by RayStick** [comment]
Okay, so in test_data you will now see some files for the multi frequency testing which should be much smaller than before:

Test1_multifreq_onescan.txt
Test1_multifreq_onescan_noheader.txt
Test1_multifreq_onescan_notime.txt

These match the files we were using before (Test_2minRest_trig_multifreq_header_comment.txt) but it's about 45 seconds of data instead of 2 minutes, and it is exported at 100Hz instead of 1000Hz.

**Comment by eurunuela** [comment]
Thanks @RayStick ! I’ll give these files a try once I get home in like an hour or two. I’ll keep you posted!

**Comment by RayStick** [comment]
Sure, thanks! 

By the way, I just realized the file that people mentioned we needed to trim had "_comment" in the file name. In my new exports I have not included "_comment" in the filename because I actually saw no comments in the data recording!

**Comment by eurunuela** [comment]
Don’t worry about it ;) I’ll make sure I select the correct file.

**Comment by RayStick** [comment]
I am going to upload some new multi-freq files.

**Comment by RayStick** [comment]
Sorry for the delay. You can try again now!

**Comment by RayStick** [comment]
So the _exported_ frequency is 1000Hz again, for all channels.

The sampling frequency for the channels was (from what I can from the orig. file):

(Time)
Channel 1 - TR - 1000Hz
Channel 2 - CO2 - 100Hz
Channel 3 - O2 - 40Hz
Channel 4 - 400Hz

**Comment by eurunuela** [comment]
Thank you so much for your help @RayStick! I've just pushed the changes to #226. It looks like we managed to reduce the testing time in another 20 seconds or so for Travis. As before, I can see no impact on testing time for Azure.

Let's see what everyone else has to say about this on Thursday.

**Comment by RayStick** [comment]
Great 👍
