### ISSUE TITLE
phys2bids June developer call (11.06.2020 @ 9.30 AM CDT/ 10.30 AM EDT / 16.30 CEST)

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#225]
Next developer call: 11th of June 2020.
The call will take place over **jitsi** [here](https://meet.jit.si/phys2bids).
Jitsi doesn't require to install any additional software but a web browser, if you want to connect by desktop (it will require to install the app to be used on handheld devices). Trying beforehand that the platform works as expected is suggested.

Find the agenda [here](https://docs.google.com/document/d/1aOZS8d-br6wfJAFaWFcRdsjEHbkA-ejL_H8wFF1EykA/edit?usp=sharing) and don't be scared to add/suggest/press for topics! 

The doodle to set the time is [here](https://doodle.com/poll/69w9uwvgygrc46d5). You have time until Saturday at 13 (Bruxelles time) to express your preference! 

Old minutes are [here](https://drive.google.com/open?id=1zfc-hgRcU1k2XdqKD8v6TGwQX_jeCUea)

There's some things OHBM-related to discuss, but especially we need to close this [milestone](https://github.com/physiopy/phys2bids/milestone/2)!

**Comment by RayStick** [comment]
I may struggle to be there at 9am, so I have only put 10-11am at the moment. 
I could do 9:30 - 10:30 though. @smoia would it be ok to add that as an option?

**Comment by smoia** [comment]
If everyone prefers 9.30/10.30/16.30 it's good to me!

**Comment by smoia** [comment]
@physiopy/all  Time of the call 9.30 AM CDT/ 10.30 AM EDT / 16.30 CEST

**Comment by smoia** [comment]
@rmarkello are you connecting? https://meet.jit.si/phys2bids
