### ISSUE TITLE
Check all-contributors is up to date

### ISSUE THREAD

**Issue by RayStick** [physiopy/phys2bids#227]
## Summary
@smoia and I noticed that the all-contributors is not up to date. Everyone should check if their symbols represent what they have contributed. 
## Next Steps
- Use the command line interface to update things or wait to merge auto
- Even after merging auto, does it update everything?

**Comment by RayStick** [comment]
For example, I should have the _reviewed-pull-requests_ and _code_ symbols and possibly others ones.

**Comment by RayStick** [comment]
I wasn't sure what to label this.

**Comment by eurunuela** [comment]
It looks fine in my case. Regarding your question about `auto`, maybe @smoia knows about it?

**Comment by smoia** [comment]
I'm curious to see which categories `auto` will handle on its own!
For sure some will have to be manually updated.

However, this is a very important step, so I would invite everyone to report here if there's a mismatch between their real contributions and those listed.

As a general rule of thumb:
  - bug-related PR shouldn't give "code" contribution but "bug" contribution (not 100% sure though)
  - "test" contribution should appear only if the tests were coded. If you did manual testing, then "User Test" should be listed instead (given that you produced and shared a report of your user testing).
  - tests and documentation written to support an enhancement from the same author should not be listed.
Those rules of thumb can be heavily rediscussed (probably we should, starting in this issue), and in any case exceptions can be made based on the amount of work (e.g. if there's extensive documentation added after an enhancement, or if the bug fixing became a huge refactoring, we should recognise the effort).

**Comment by smoia** [comment]
@physiopy/phys2bids please all have a look!

**Comment by RayStick** [comment]
If we want to make sure this up to date before the BrainHack/OHBM conference (<I assume that would be good?), I suggest that @physiopy/phys2bids contributors either:

1. Just react with a 👍 on this post if everything looks fine for you. 
2. Comment explaining what emojis are missing for you.

**Comment by RayStick** [comment]
If I understand all the labels correctly, I think I should have: bug reports, **code**, data, documentation, **ideas planning & feedback**, **reviewed pull requests**, user testing. So the ones in bold are missing.

**Comment by sangfrois** [comment]
Hey @RayStick 
thanks for checking this out with everyone. I'm not sure where I stand as #206 is going through some changes. I don't know if I'm considered as a contributor as of now. If I can get someone's input on that, it would be much appreciated.

**Comment by RayStick** [comment]
@sangfrois - this is a good point. I am probably not the best person to make a call on this but I would suggest that your involvement of organizing the [OHBM schedule](https://github.com/physiopy/phys2bids/issues/233) should be recognized with an emoji (maybe **ideas, planning & feedback**? but I am not sure) which would get you on the contributor list before your code has been merged. But let us see what others think.

**Comment by eurunuela** [comment]
> @sangfrois - this is a good point. I am probably not the best person to make a call on this but I would suggest that your involvement of organizing the [OHBM schedule](https://github.com/physiopy/phys2bids/issues/233) should be recognized with an emoji (maybe **ideas, planning & feedback**? but I am not sure) which would get you on the contributor list before your code has been merged. But let us see what others think. 

I think that’s fair. We cannot give you the coding badge yet as the code isn’t part of phys2bids right now.

**Comment by smoia** [comment]
@sangfrois @RayStick @eurunuela , @rmarkello proposed to add François in the list of authors of the OHBM poster. I didn't know it was possible, but if it is, I think it's a fair acknowledgement of his contribution until now.
For the contributors table, I'm sorry to say that "ideas & planning" seems to be more related to coming up with new ideas and organise their development, so I don't think #233 is enough to get the badge.
@sangfrois , I think that the best thing we can do considering everything is to finish #206 and merge it in ASAP - so that you can get a code contribution badge before OHBM and @tsalo can continue developing #218. 
After all, at the moment being one of the recognised contributors in GitHub is what matters - so that when people will visit the page or use the software, we'll all be named (especially in zenodo).

So, let's not despair and let's get what is left to do in #206 (with testing) done!

**Comment by sangfrois** [comment]
Totally agree with you for #233. 

Thanks for taking the time to disambiguate the situation.

As I can't edit the PR message for multirun workflow improvement, I will comment to detail what I meant.

**Comment by eurunuela** [comment]
I'm thinking we should probably specify how and when we're going to recognize contributions to phys2bids. After the discussions we had in this issue, and me personally not knowing when one should be recognized with the "ideas" emoji for example, I feel like this is something that's not very clear at the moment.

Should we specify it in our documentation? For example in the contributing guidelines? Bringing this up for dicussion.

**Comment by sangfrois** [comment]
@eurunuela I think you're bringing up a great suggestion. Adding this into the docs would certainly help, or at least, it would give new contributors something to start with if they have questions or doubts about their contribution.

From my standpoint, I wasn't sure at what point I would be considered as a contributor even though I would spend hours working on the project. Nothing stressing, but still : uncertainty.

So yeah, let's talk it over more in jitsi, I like the idea of having some information in the docs.

**Comment by eurunuela** [comment]
I'd keep the discussion in this issue as not every contributor is taking part in the OHBM BrainHack. We could continue the discussion in our next meeting too.

**Comment by smoia** [comment]
@tsalo you have a bit more experience across the board... what's the general approach to this?

(PS: we can also open the discussion to other people that are not in `phys2bids`)

**Comment by tsalo** [comment]
TBH I think that @emdupre and @jbteves have been the ones who have handled the `all-contributors` updates in `tedana`. I haven't really touched it. I don't remember seeing either of them discuss updating the contributor badges much, and I think everyone's been happy with their choices generally. The difference between `tedana` and `phys2bids`, though, is that the all-contributors list is separate from the set of contributors who will be listed on posters or included in manuscripts. The process for defining the devs team or authors on scientific works hasn't been formalized, I don't think.

**Comment by jbteves** [comment]
`tedana` definitely has a separate contributor and author list. I think @emdupre has been more on top of it than I have. As a general rule for any PR with a contribution type not already noted in our contributor list, I'll comment to have the new contribution type added just before approval. This seems to work alright but memory is fallible and so sometimes things go missing. Full automation for this type of thing strikes me as difficult. Author choices for posters are a little bit more subjective, but so far we're not aware of complaints. I do believe that posters are usually specifically targeted towards people who have contributed on a consistent basis rather than a one-off, focusing on contributions since the last OHBM poster. @emdupre please correct me if you disagree with any of this.

**Comment by smoia** [comment]
The process of defining authors in scientific works is a topic during our next meeting. For the moment, there's a complete overlap with the all-contributors (that overlap with the dev team).
The main question here is "how do we interpret the all-contributors specification?"
Up until now, I tried to match other libraries use of it (then, today I had a look at tedana's all-contributors and some of my believes crashed into nothing).
Reading [here](https://allcontributors.org/docs/en/specification) and [here](https://allcontributors.org/docs/en/repository-maintainers), all-contributor suggests to write a specific guide on how contributions are recognised - which we should do.

If @physiopy/all agree, I can start compiling a guideline for it, and then we can discuss it once there is a document to discuss on.

I would still love others to pitch in and leave an opinionated thought about it though!

**Comment by eurunuela** [comment]
@sangfrois the new GitHub UI makes it easier to see who has contributed with commits. See the picture. SO you're somehow recognized by GitHub while we decide how we're using the allcontributors bot from now on.
![image](https://user-images.githubusercontent.com/13706448/85129836-18108200-b234-11ea-95ab-e434e7aa8289.png)

**Comment by eurunuela** [comment]
Hey @smoia , I think @tsalo should get the PR review emoji 😉
