### ISSUE TITLE
Multi-frequency files 

### ISSUE THREAD

**Issue by RayStick** [physiopy/phys2bids#228]
In Issue #221 - this was the first time I have interacted with exporting multi-frequency files from our LabChart software. Even though I can see that the channels were _sampled_  at different frequencies (1000Hz for trig, 100Hz for CO2, 40Hz for O2, 400Hz for Belt) when I _export_ this file to a txt file I have to choose a frequency to export (e.g. 100Hz) so I assume that some channels get upsampled and some downsampled for this to happen. Therefore, I am not sure if we would need to deal with these mutli-freq files differently in our code as they are now, effectively, at the same frequency in the export file. Or am I missing something?

The files I am referring to:

Originally we used _'Test_2minRest_trig_multifreq'_ ... which was in _labchart/chicago_
I have cut and re-exported these files and they are now called _'Test1_multifreq_onescan'_ in _test_data_

@vinferrer do you have any thoughts? As you've interacted with these multi frequency files the most I think (for testing)?

**Comment by RayStick** [comment]
And I'll also tag @smoia because he uploaded 'Test_belt_pulse_multifreq.acq' to OSF so may have thoughts.

**Comment by smoia** [comment]
@RayStick BIDS specifications ask for a file for each frequency. While wfor acq files this step is made easy by just importing the file with `bioread`, for LabChart derived txt files it's a bit trickier. In fact, if you export the file at the highest frequency recorded, the channel with lower frequencies have repeated entries to cover for the missing ones (e.g. in a file exported at 1000Hz, a 100Hz channel will have for each value 10 entries that are the same to cover the same amount of samples as the channels sampled at 1000Hz). It's true that we could skip the multifreq check for such files, but we would have heavier files that are _fake_-sampled at higher frequency, and in any case the multifreq check has to be run for AcqKnowledge derived txt files, so I guess the multifreq check code would be run anyway (but @vinferrer definitely knows better than me if that's the case). So we wouldn't save much resources and end up with a solution that seems suboptimal, especially since the code is already implemented.
We can discuss whether it's the case to skip the multifreq check on txt files or not. Personally, I don't see why we shouldn't run them, but if there's a good reason to skip that part, I'm all in for that!

**Comment by RayStick** [comment]
Ah I see. Yeah, if you already have to run the tests for AcqKnowledge files, the work has already been done, so we might as well run them on txt files (just with the knowledge that, at the moment, some channels will be saved in a frequency that was not necessarily their sampled frequency). 

I could export separate txt files for each channel, at each of their individual sampling frequencies, if that helps for future testing?

**Comment by eurunuela** [comment]
AFAIK the multi-freq test is only done on a txt file.

**Comment by RayStick** [comment]
So would it make more sense to do it on an AcqKnowledge file? (If only testing one of them)

**Comment by vinferrer** [comment]
Yeah so right now the multi-freq test works on txt files. What the function does is enter into each channel and taking the base frequency, which is the highest, it looks if there is repeated values. If there are and this is common in the hole file, it means that specific channel has a lower frequency. AcqKnowledge format files reading was developed by @smoia. So I stuck to my side of the format reading, which is txt files (could be acqknowledge or labchart, doesn't matter).

**Comment by vinferrer** [comment]
If I recall correctly, acqKnowledge format files do not require multifreq testing since the frequency is in the header. However in txt this is not the case, that's why we developed this feature. I hope this was clarifying

**Comment by vinferrer** [comment]
We could easily add a test for the acqKowledge files

**Comment by vinferrer** [comment]
But as you can see in: https://github.com/physiopy/phys2bids/blob/79403c9ac5240e8f1d1cfe95820fc804b829574f/phys2bids/interfaces/txt.py#L252
The check is included in the process_acq function

**Comment by eurunuela** [comment]
My bad. We do use an ACQ multi-freq file in the integration test! Had completely forgotten about it.

**Comment by smoia** [comment]
Ok, sorry, I was probably not clear:
`acq` files do not need a multifreq test. Those files are imported as an object that contains the frequencies already.
`txt` files _coming from AcqKnoweldge_ do need such a feature (although I don't remember how they are organised internally atm).
I would like to change the question that started this issue into this one:
### What benefit would we get by skipping the multifreq check, hence the file separation into different tsv files, on the txt format?
@RayStick, are you talking about tests instead? If so, what is the doubt?

**Comment by RayStick** [comment]
Sorry, I was not clear with some of my wording. When I said "txt" I always meant LabChart txt files. 

@vinferrer thanks for explaining, that makes more sense now - that you are specifically testing for different lower frequencies by looking for repeated values, as I did not know that. I guess I am talking about multifrequency checks in the code then, not these tests. But I do have a related question about tests:

 In order to make the multifreq labchart txt file smaller in size I did these things:
1. Exported ~45s data instead of 2 mins
2. Exported at 100Hz instead of 1000Hz. 

Do we think step 2 is ok? Considering that the channels were recorded at 1000, 100, 40, 400Hz. 

I ask because I do not fully understand the multifreq check or the some of the tests so just want to be clear with what I have done in case in interacts with either of them.

**Comment by eurunuela** [comment]
@RayStick I've just run the test and it fails. I believe step 2 is incorrect. See the error:

```bash
E   assert [100.0, 100.0, 50.0] == [100, 40, 500]
E     At index 1 diff: 100.0 != 40
E     Use -v to get the full diff
```

The file seems to have two channels at 100.0 Hz and not the 100 Hz and 40 Hz channels.

**Comment by RayStick** [comment]
Ah, I see. Now I understand a bit more, I think the fact that I have downsampled in my export may be causing a problem. I could try to upload the files again - still short in length (45s) but exported at 1000Hz which means that we only have upsampling (repeated values) and not downsampling.

**Comment by eurunuela** [comment]
Let’s see if that works but @smoia and @vinferrer probably know better.

**Comment by vinferrer** [comment]
> 
> 
> @RayStick I've just run the test and it fails. I believe step 2 is incorrect. See the error:
> 
> ```shell
> E   assert [100.0, 100.0, 50.0] == [100, 40, 500]
> E     At index 1 diff: 100.0 != 40
> E     Use -v to get the full diff
> ```
> 
> The file seems to have two channels at 100.0 Hz and not the 100 Hz and 40 Hz channels. The left side of the assert line is what phys2bids returns, while the right side is what we expect.

That's weird, Do you guys think is worth checking?

**Comment by vinferrer** [comment]
Maybe if the file is downsampled the multifreq function does not work properly anymore, I didn't take into account that posibilty

**Comment by RayStick** [comment]
Yeah I think the check you explained is probably dependent on it not being downsampled.

**Comment by eurunuela** [comment]
It makes sense that the multi-freq doesn’t work with the downsampled data. You’re reducing your sampling rate so you won’t be able to read anything above that frequency.

**Comment by vinferrer** [comment]
However, in the error you have in that assert the contrary happens. We are failing to detect a lower frequency, which in this case is 40 Hz. I think this could be a problem

**Comment by vinferrer** [comment]
I think we can discuss it on #225

**Comment by RayStick** [comment]
Shall we close this issue now? I _think_ we decided it was resolved in the phys2bids call? But I may have missed some details as my internet connection was bad.  (The multi-freq _tests_ won't work if someone has downsampled data beforehand, but that makes sense. Maybe just a note in the documentation making that clear for the user?)

**Comment by eurunuela** [comment]
I’ll close it. Feel free to re-open if necessary.
