### ISSUE TITLE
Testing new multi-run pipeline and related changes

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#230]
## Summary
In #206 many code changes were made. Unluckily, mainly due to lack of time, we didn't make enough tests, and the code coverage dropped.

We need some more testing to make the code coverage raise again above the 90% threshold.

## Next Steps

- [ ] Test the new function in `viz.py`
- [ ] Add tests for the native objects (`physio_obj.py`)
- [ ] Add breaking tests (they're fun)

**Comment by eurunuela** [comment]
What do you mean by "new function in `viz.py`?

**Comment by smoia** [comment]
@eurunuela @sangfrois @vinferrer don't we have new tests now? Should we close this issue?

**Comment by eurunuela** [comment]
Yes, I think we can close this.
