### ISSUE TITLE
Improving split of multiple runs

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#232]
## Detailed Description

Reporting from #206 on @sangfrois behalf:

> The next step will be to reduce user's inputs in ``phys2bids`` by detecting the number of triggers in each run automatically.
> Either by looking in the DICOM registry or directly computing the time difference between subsequent triggers.
> That way, an individual file will require less attention to pass through phys2bids workflow, and the user will be able to process batches of files.

@sangfrois, could you please explain a bit more what you meant? You can edit this message and complete it as you think is more appropriate.

**Comment by sangfrois** [comment]
(I can't edit your description)

**Comment by tsalo** [comment]
> Either by looking in the DICOM registry or directly computing the time difference between subsequent triggers.

@sangfrois this sounds similar to #219, which detects missing trigger periods (and missing scans) by comparing the time differences for both physio triggers and scan onsets from the BIDS dataset.

**Comment by sangfrois** [comment]
@tsalo Yes, exactly.

let's have touch base in jitsi room during the breakout session of the hackathon to discuss everything!

I'm having difficulty grasping every aspect of your PR, and am sure we can join forces!

**Comment by smoia** [comment]
@sangfrois can we close this issue?

**Comment by sangfrois** [comment]
@smoia yes absolutely
