### ISSUE TITLE
auto doesn't find the Github token when running in Travis

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#239]
@hipstersmoothie we may need your help here.

@eurunuela and I merged in the PR to run auto, but at the moment [Travis says it's missing a token](https://travis-ci.org/github/physiopy/phys2bids/jobs/698514747).
I created the token a while ago, so I don't understand why it's not working. Should I create a token for the organisation?

Could you have a look at our configuration?
[This is Travis config](https://github.com/physiopy/phys2bids/blob/master/.travis.yml)
[This is auto](https://github.com/physiopy/phys2bids/blob/master/.autorc).

**Comment by hipstersmoothie** [comment]
Is the token available on the necessary branches

**Comment by eurunuela** [comment]
Any update on this @smoia ?

**Comment by smoia** [comment]
I had zero time to look at this, probably won't do it before the end of next week unluckily.

**Comment by eurunuela** [comment]
Now that we do not use Travis, we should see how auto works with CircleCI.

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.2.1`](https://github.com/physiopy/phys2bids/releases/tag/2.2.1) :rocket:
