### ISSUE TITLE
Empty fields in participants.tsv

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#252]
This discussion is related to #244.

I'm opening this discussion because we should decide whether we want to have a "n/a" (not answered) field or if phys2bids should only write the subject id in participants.tsv. The "n/a" would "advice" the users they should be adding that info following BIDS guidelines.

So, there are two possible options here (feel free to add more):

1. Only write subject ID and other fields provided in the YAML file.
2. Write the three BIDS recommended fields as "n/a" when they're not provided in the YAML

I'd like to know what you think @smoia @vinferrer @tsalo @robertoostenveld

**Comment by tsalo** [comment]
I say we take our cue from heudiconv, which adds those columns (along with "group") and puts a `n/a` if the information is unavailable.

**Comment by smoia** [comment]
@marcelzwiers, what is the behaviour of BIDScoin?

**Comment by marcelzwiers** [comment]
In Bidscoin I use the `n/a` value, like this (participants_table is a pandas dataframe):
```
    if participants_tsv.is_file():
        participants_table = pd.read_csv(participants_tsv, sep='\t')
        participants_table.set_index(['participant_id'], verify_integrity=True, inplace=True)
    else:
        participants_table = pd.DataFrame()
        participants_table.index.name = 'participant_id'

 [...]

participants_table.replace('','n/a').to_csv(participants_tsv, sep='\t', encoding='utf-8', na_rep='n/a')
```

**Comment by smoia** [comment]
Given that the two DICOM bidsifiers we're adopting as reference have a "n/a" value for missing field, I would do the same.
I think this is the current behaviour, right @eurunuela? If so, and there is no strong opinion against it, we can close this issue.

**Comment by eurunuela** [comment]
That's the current behavior. Closing the issue then.
