### ISSUE TITLE
Should duecredit be a required or optional dependency?

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2bids#253]
## Summary

#249 sets duecredit up as an optional dependency, but the devs should decide whether they want it as an optional or required dependency.

[duecredit](https://github.com/duecredit/duecredit) is a package for associating citations with code. The developer add decorators to functions with the appropriate citations for those functions. Then, when the users runs the code, they can use a duecredit command to collect all citations for all functions run, and get an annotated bibliography that they can incorporate into their manuscript.

## Additional detail

This stems from https://github.com/physiopy/phys2bids/pull/249#pullrequestreview-432541991.

## Next Steps

- Discuss

**Comment by tsalo** [comment]
I vote optional, FWIW. That's how we do it in `tedana` and `NiMARE`. The drawback is that making it an optional dependency means we need to include the `due.py` stub file in the repository to prevent import errors.

**Comment by smoia** [comment]
@tsalo , could you explain a bit more what is duecredit and why we should be using it? I'm not sure all of the physiopy developers know what it is!

**Comment by eurunuela** [comment]
Optional sounds good to me!

**Comment by tsalo** [comment]
@smoia I updated the issue summary. Thanks for catching that.

**Comment by smoia** [comment]
I guess optional it is!
I'll close this since it's the current setup.
