### ISSUE TITLE
Add 'auto' option for populate_phys_input chtrig parameter

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2bids#257]
Users may not know which channel is the trigger channel, so it would help them to be able to auto-detect the trigger channel and, in the absence of useable information, raise an error with the names of the available channels.
## Context / Motivation

For any user who doesn't know/remember what their trigger channel is, they have to load the data to a `BlueprintInput` with some random number set as the trigger channel, check the channel names, and then re-load the data with the correct trigger channel index. This should streamline the process in those cases. Plus, it would simplify the standard loading procedure in that there would only be one required argument to the function.

## Possible Implementation

- [ ] Create an alias list with "trig", "trigger", "TRIGGER", [...]
- [ ] raise a warning if the trigger channel's name does not contain any element in the alias list
- [ ] if the user didn't give a trigger channel, we look into the names and check if there is a match to any element of the alias list. If there is not, we raise an error.

**Comment by eurunuela** [comment]
Is this related to #204 ?

**Comment by smoia** [comment]
This seems to be half way between #204 and the reason we have `-info` as an argument (to check files before running batches of phys2bids). What does it adds on top of the behaviour of `phys2bids -info` option?

**Comment by tsalo** [comment]
I wasn't aware of `-info` when I opened the issue (my bad!), but there are still going to be users who don't use the workflow. Regarding #204, this is a much simpler solution to a much smaller problem. Instead of looking at the signal, this just looks at the channel names.

**Comment by smoia** [comment]
What do you think if instead:

a. we create an alias list with "trig", "trigger", "TRIGGER", [...]
b. we raise a warning if the trigger channel's name does not contain any element in the alias list
c. if the user didn't give a trigger channel, we look into the names and check if there is a match to any element of the alias list. If there is not, we raise an error.

Reasoning: During data acquisition it's not granted that you are calling your channels "trig". If you don't have it in your channel names, rasing an error will make phy2bids not able to do its job. However, we can help a bit the user.

**Comment by tsalo** [comment]
Absolutely. This would be perfect! So there's still an 'auto' option, but it's far more robust than what I originally planned, right? Plus a new check even when the trigger channel is provided.

**Comment by vinferrer** [comment]
I think this is a good thing to implement, however we are gonna have to wait for #273. Since it will affect the ``chtrig``.

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.4.0`](https://github.com/physiopy/phys2bids/releases/tag/2.4.0) :rocket:
