### ISSUE TITLE
Change floats print format

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#26]
Currently, any print of a float in a file has a format with many decimals.
It would be better to have a formatted print with max 4 decimals.

This doesn't affect the data, only the information in the json and in the log.

**Comment by eurunuela** [comment]
@sangfrois would you like to try this one?

**Comment by smoia** [comment]
Anyone willing to take this?

**Comment by RayStick** [comment]
I can do this!

**Comment by sangfrois** [comment]
Sorry, I never saw this! Hehehe
