### ISSUE TITLE
Multi run generates trigger plot without 0 before run number

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#265]
## Expected Behavior

Following the file naming style generally used by the multi-run pipeline, I guess one would expect the trigger plots to have the following file name `Test2_samefreq_TWOscans_01_trigger_time.png`.

## Actual Behavior

However, the multi-run pipeline saves trigger plots as `Test2_samefreq_TWOscans_1_trigger_time.png`.

## Steps to Reproduce the Problem

    1. Update phys2bids to latest version in master as of June 23rd.
    2. Run the following command `phys2bids -ntp 534 513 -tr 1.2 1.2 -chtrig 1 -in Test2_samefreq_TWOscans.txt`
    3. Check for trigger plots in the code/conversion directory.

## Specifications

    - Python version: latest version in master as of June 23rd.
    - phys2bids version: v2.1
    - Platform: MacOS Catalina

## Possible solution

Use the same formatting used everywhere else by the multi-run pipeline.

**Comment by eurunuela** [comment]
Was this fixed @vinferrer ?

**Comment by vinferrer** [comment]
I think is the first time i see this issue so i don't think so

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.3.2`](https://github.com/physiopy/phys2bids/releases/tag/2.3.2) :rocket:
