### ISSUE TITLE
phys2bids July Community call (09.07.2020 @ 14.30 UTC / 9.30 AM CDT/ 10.30 AM EDT / 16.30 CEST)

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#271]
The call will take place over **jitsi** [here](https://meet.jit.si/phys2bids).
Jitsi doesn't require to install any additional software but a web browser, if you want to connect by desktop (it will require to install the app to be used on handheld devices). Trying beforehand that the platform works as expected is suggested.
This is the last chance we give to jitsi, if we see that it doesn't work, we'll change back to Skype.

Find the agenda [here](https://docs.google.com/document/d/1hYq42cTY8fYxuSfdQIXV-lN_CUrw4Xos00Dqha7qGUI/edit?usp=sharing) and don't be scared to add/suggest/press for topics! 

Please have a look at the peakdet repo and at physio_obj.py in this repo.
Also, if you want to suggest developments, open as many issues as you want! We'll decide the next milestone during the meeting.

Old minutes are [here](https://drive.google.com/open?id=1zfc-hgRcU1k2XdqKD8v6TGwQX_jeCUea).

**Comment by RayStick** [comment]
Really sorry everyone @physiopy/phys2bids  - I completely missed this call today!

**Comment by RayStick** [comment]
But thank you for the minutes :)

**Comment by eurunuela** [comment]
No problem @RayStick !

**Comment by tsalo** [comment]
Can this be closed?
