### ISSUE TITLE
Refactor interfaces/txt.py use of chtrig channel

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#273]
After the discussion in #272 , I understand how the current use of `chtrig` in `interfaces/txt.py` can lead to confusion.
I'd propose a very quick, very neat refactoring to lower the chances of confusion while reading the code

## Detailed Description

In [this line](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L152) and [this line](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L251), `interfaces/txt.py` initialise a `BlueprintInput` object with `chtrig +1` as trigger channel.
This could be thought coming from the idea that the first channel becomes time, however it's due to the fact that upstream in the process, [here](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L322), `chtrig` is decremented by 1. This could lead to confusion in understanding the script, especially since `chtrig` is not used in any other place than the `BlueprintInput` initialisation.

## Possible Implementation

- [ ] Delete [line 322](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L322)
- [ ] Remove chtrig from [this definition's argoments](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L254), since it's not used in the definition itself.
- [ ] Change `chtrig +1` in [this line](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L152) and in [this line](https://github.com/physiopy/phys2bids/blob/a2493bf383d3a7668c549099215bd3ddd60f8831/phys2bids/interfaces/txt.py#L251) into `chtrig` only.
- [ ] Add explanation of `chtrig` indexing starting from 1 for human readability in all the docstrings.

I'm going to add a Good First Issue label since it should be not that hard. @RayStick you're still the guardian of G1Fs.

**Comment by vinferrer** [comment]
Did we stablish a limit on how much time a good first issue can be unresolved?

**Comment by vinferrer** [comment]
Since This issue is affecting the implementation of #257 we should move to implement this. If someone with less experience in scripting the toolbox wants to try good. If not I am happy to do this quickly

**Comment by eurunuela** [comment]
I'd say you could start to work on it, it's already been two months.
