### ISSUE TITLE
Add (resampled) trigger channel in every multifreq output

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#274]
This comes from #219. It would be a good idea (not mandatory, but good) to add a refactored trigger channel in each output in case of multiple outputs due to multifrequency files.
At the moment we're not doing it!

## Context / Motivation

It would help improving (visual) comparison between traces and fMRI trigger!

## Possible Implementation

- [ ] Create a resampled trigger channel for each (unique) frequency encountered in `BlueprintInput.freq` list (e.g. with `set(BlueprintInput.freq)` or `np.unique(BlueprintInput.freq)`) and append it to the channel list. This could be a class method.

**Comment by vinferrer** [comment]
i can take care of this at some point, it should be quite easy since the trigger is "always" in the greatest frequency
