### ISSUE TITLE
Reorganize I/O functions

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2bids#295]
## Summary

I find the `phys2bids.interfaces.[modality].populate_phys_input()` structure unnecessarily confusing. Why not have `phys2bids.io.load_matlab()`, `phys2bids.io.load_text()`, and `phys2bids.io.load_acq()`?

Note: this stems from https://github.com/physiopy/phys2bids/pull/292#issuecomment-676525617.

## Additional detail

I understand the potential benefits to having multiple functions with the same name (e.g., if you wanted to use `eval` and such to call functions), although, even in those cases, I don't know if it's worth the confusion. In `phys2bids`' case, however, the functions are called directly in the relevant code, so there isn't much benefit to this structure.

Also, `populate_phys_input()` as a function name mostly makes sense if you have multiple classes you might want to read in from files. In `phys2bids`' case, though, you really just want to read them into `BlueprintInput` objects (e.g., you're not going to read an acq file into a `BlueprintOutput` object), so I don't think there's any need to be so specific about the function name. A generic `load_` or `read_` should be sufficient.

## Next Steps

* Move the relevant functions to the same submodule (`phys2bids.io`). If you're concerned about their respective imports, you can just move the tool-specific imports into the function definitions.
* Rename the functions from `populate_phys_info()` to `load_matlab()`, `load_acq()`, and `load_text()` (or similar).
* Update tests and API documentation.

**Comment by tsalo** [comment]
I'm happy to do this once #292 is merged, unless anyone has any issues with the proposed change.

**Comment by eurunuela** [comment]
I'd appreciate that @tsalo

**Comment by smoia** [comment]
Right, we _could_ do that actually - I don't have a strong opinion against it, as long as the imports are in the function definitions.
Since you're there, actually trying the imports and otherwise break the code with a message that tells the user to install the missing library would be awesome!

**Comment by vinferrer** [comment]
What if we just do this and then add the matlab thing. I have been working in it with eneko and we arrived to the conclusion that we are gonna duplicate code

**Comment by eurunuela** [comment]
I think it makes more sense to do the refactoring first. We have realized that adding support for Matlab requires using code that has already been written for acq files.

**Comment by tsalo** [comment]
I know I agreed to take this on (and would be happy to if this was happening next week or something), but I'm pretty buried. Would someone else be willing to do the refactor? I'm happy to review.

**Comment by vinferrer** [comment]
I can do it, most of the funtions are mine actually

**Comment by vinferrer** [comment]
but for sure not during the brainhack, this requires deep reorganization

**Comment by vinferrer** [comment]
So We can to 2 things:
1. Do a tiny PR that Move the relevant functions to the same submodule (`phys2bids.io`). Rename the functions from populate_phys_info() to load_matlab(), load_acq(), and load_text() (or similar). Update tests and API documentation.
2. A bigger PR after 1 that reorganizes this and avoids duplicated code. specially for the load_txt part.
What do you think?

**Comment by smoia** [comment]
Wait, are you thinking about creating a submodule?

**Comment by vinferrer** [comment]
I am thinking about putting together phys2bids.interfaces.acq and phys2bids.interfaces.txt into phys2bids.interfaces.io

**Comment by vinferrer** [comment]
The second PR would be about changing that `txt.py` code so there is no so many duplicities

**Comment by eurunuela** [comment]
Sounds good to me! Thank you Vicente.

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.3.0`](https://github.com/physiopy/phys2bids/releases/tag/2.3.0) :rocket:
