### ISSUE TITLE
Deal with "non-required" packages for interfaces.

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#30]
One of the issues of having to deal with multiple type of files in input is that some of them (acqknowledge, matlab) requires libraries to load the content of the files.

However, such libraries are necessary only reading those files, and it's possible that a succesful run of the program doesn't require them.

It's easy to import them only if needed, but the question is:
**should they be required (hence automatically installed) during the setup of phys2bids, or should we throw an error if they're missing and ask to install them later?**

**Comment by smoia** [comment]
@rmarkello what do you think on this matter?

**Comment by rmarkello** [comment]
I *think* I'd lean towards the latter&mdash;throw an error if they're required but not installed&mdash;but this is going to depend on the code set up a bit... That is, it might be hard to determine which imports are needed without having them installed already.

Let me take a look at how you've structured things in #38 and maybe that will provide some insight!

**Comment by smoia** [comment]
@rmarkello @vinferrer @eurunuela @RayStick @sangfrois, what do you think about this issue? If we lean toward not installing them by default, we can close this issue.

**Comment by eurunuela** [comment]
I'd stick to what @rmarkello was suggesting; i.e. throw an error if a required package is not installed.

**Comment by rmarkello** [comment]
What are we considering "non-required" packages now? For the time being, just `bioread`?

**Comment by eurunuela** [comment]
I think that's the only one right now, yes.

**Comment by rmarkello** [comment]
Gotcha!

I think in _general_ I'd be pro-"throw an error if it's not installed" as I said before, but `bioread` is actually pretty light-weight. It only depends on `numpy` and the [tarball](https://pypi.org/project/bioread/#files) on PyPi is ~40kB, so including it as a required dependency doesn't seem to be too unreasonable 🤷‍♂ 

That said, if you think the number of optional dependencies is going to get larger over time and want to stick with a hard-and-fast "optional dependencies aren't installed" rule now, I'm happy to follow suit.

**Comment by smoia** [comment]
I see your point, but as you say the number of optional dependencies might increase later on.
For instance, if/when we start supporting matlab files, we would have other libraries to add to the list.
Another thing I'm puzzled about is the fact that the more libraries we depend on, the more we are at risk of deprecation errors (we already receive warnings from `bioread`).
It seems to me that the general opinion is toward simplifying dependencies, I'll follow that road!

**Comment by rmarkello** [comment]
Totally fair! I'm not well-positioned to know how many "new" libraries `phys2bids` may end up needing, so simplifying dependencies now sounds good to me.

(Regarding `DeprecationWarnings`: We could also consider making an upstream PR to `bioread` to fix those! I'm sure they'd appreciate it 😎)
