### ISSUE TITLE
build_docs artifact job points to wrong build

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2bids#300]
## Summary

The `build_docs artifact` status check uses [`circleci-artifacts-redirector`](https://github.com/apps/circleci-artifacts-redirector/) to provide an easy link to the CircleCI-built documentation. However, the status check link, across PRs, consistently points to a nonexistent artifact. I haven't seen this problem in other repos I know that use this app, including `NiMARE`, `bids-specification`, and `rapidtide`.

This stems from https://github.com/physiopy/phys2bids/pull/297#issuecomment-676553193.

## Additional detail

I'm sure this is a matter of settings on CircleCI and/or on repository forks, but altering phys2bids' settings to match those of other projects I contribute on didn't fix the problem.

## Next Steps

I'm not sure. If someone has the time to dig into this, that would be great. Some potential steps there:
- Compare settings with functioning projects that use the same app.
- Search `circleci-artifacts-redirector` repository for issues (both open and closed) related to this problem.
- Search StackOverflow. There probably won't be issues about this specific app on there though.
- Check with PR openers about their own CircleCI settings. Are they running CI on their forks independently of the main repo? If so, maybe those secondary builds are what the app is registering and pointing too.

**Comment by eurunuela** [comment]
My CI is running on my fork independently. That may be the reason but I still do not understand what's wrong. `phys2bids -v` always returns the latest version to me.

**Comment by tsalo** [comment]
The issue is that the `build_docs_artifact` step isn't resolving a URL to the same place where the actual docs artifacts are (from the `build_docs` step). `build_docs_artifact` _should_ just point to the `index.html` file uploaded to CircleCI's artifacts from `build_docs`, so you can view the RTD site with a single click.

Here are the URLs for the actual index.html files for the `build_docs` step and the `build_docs_artifact` step:
https://513-221491076-gh.circle-artifacts.com/0/tmp/src/phys2bids/docs/_build/html/index.html
https://513-208861898-gh.circle-artifacts.com/0/tmp/src/phy2sbids/docs/_build/html/index.html

You'll notice that the only difference is the set of numbers right after the build number (513). For the correct URL, it's `221491076`. For the incorrect one, it's `208861898`.

I _think_ that everyone running their own CircleCI could be causing this, since #320's _actual_ URL points to Vicente's `phys2bids` repository instead of `physiopy`'s. The same goes for your own PRs.

When I look at other projects I have admin access to on CircleCI (e.g., `NiMARE` and `tedana`), I notice that my own forks do not have CircleCI pipelines. For example, https://app.circleci.com/pipelines/github/ME-ICA/tedana has all of the CI runs we've done on PRs, while https://app.circleci.com/pipelines/github/tsalo/tedana is empty. Conversely, in `phys2bids`, all of the PR CI workflows show up under the _fork's_ account.

I also just noticed that there's a typo in the path for the artifact forwarder:
https://github.com/physiopy/phys2bids/blob/13984a142a481ad6511df5da261f42d47dfe3e25/.circleci/artifact_path#L1

`phy2sbids` should be `phys2bids`. I'm not sure if fixing that will fix the problem for PRs from forks with CI running, but it should fix it for all of the others!

**Comment by tsalo** [comment]
@eurunuela If we merge #331 and you can update from `master` to merge those changes into one of your PRs (e.g., #243), we can see if it's a problem that you're running CI as well.

**Comment by eurunuela** [comment]
I'll have to do that tomorrow. Thank you @tsalo !

**Comment by eurunuela** [comment]
Thank you so much for your help @tsalo !

> When I look at other projects I have admin access to on CircleCI (e.g., `NiMARE` and `tedana`), I notice that my own forks do not have CircleCI pipelines. For example, https://app.circleci.com/pipelines/github/ME-ICA/tedana has all of the CI runs we've done on PRs, while https://app.circleci.com/pipelines/github/tsalo/tedana is empty. Conversely, in `phys2bids`, all of the PR CI workflows show up under the _fork's_ account.

How can we do that? What CircleCI settings do we have to change?

> I also just noticed that there's a typo in the path for the artifact forwarder:
> https://github.com/physiopy/phys2bids/blob/13984a142a481ad6511df5da261f42d47dfe3e25/.circleci/artifact_path#L1

I just merged with the fix in #331 and still see the wrong build number.

**Comment by eurunuela** [comment]
Okay, I solved it @tsalo . In the _Projects_ page I had to unfollow _phys2bids_. That was making the tests run on my fork instead of the main project.

This said, I will now check which of the open PRs have the wrong build on the tests and ask the contributors to do this.

Thank you for your help once again @tsalo !
