### ISSUE TITLE
Tests output files are not deleted

### ISSUE THREAD

**Issue by vinferrer** [physiopy/phys2bids#304]
Some files are not deleted once tests are finished.

## Expected Behavior
Tests should not leave any files or folders.

## Steps to Reproduce the Problem

![image](https://user-images.githubusercontent.com/38909338/93305810-53085e80-f7ff-11ea-8370-68f4e05f4f4c.png)

## Specifications
    - Python version: Python 3.6.9
    - phys2bids version: phys2bids v1.3.0-beta+1033.gc02826e
    - Platform: Ubuntu

## Possible solution
This is probably caused by the ``test_integration.py``

**Comment by tsalo** [comment]
I'd recommend using a [`tmp_path_factory`](https://docs.pytest.org/en/stable/tmpdir.html#the-tmp-path-factory-fixture) to handle your testing-related folders.

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.2.1`](https://github.com/physiopy/phys2bids/releases/tag/2.2.1) :rocket:
