### ISSUE TITLE
WSL windows installation

### ISSUE THREAD

**Issue by vinferrer** [physiopy/phys2bids#319]
## Phys2bids is able to work in ubuntu 20 Windows Subsystem for Linux version in windows 10 1904
    - I have been tweaking with my windows 10 system and I manage to install correctly phys2bids, process files and access them from windows. 
    - I believe we could add this installation in the docs for Windows.
    - I would like to bring this to discussion

**Comment by vinferrer** [comment]
Which leads me to the question, how do you do the test in windows @eurunuela ?

**Comment by smoia** [comment]
Good point @vinferrer! @physiopy/all, what's your point of view? If this works, we could just drop Windows testing altogether, no?

**Comment by vinferrer** [comment]
Well, the thing is that WSL is more a developer option, so if we have windows support and we can install it in windows I would put that installation in the docs

**Comment by vinferrer** [comment]
I did in my computer because now i don't need to change from windows to ubuntu to work in phys2bids but that's all

**Comment by eurunuela** [comment]
> Which leads me to the question, how do you do the test in windows @eurunuela ?

I would need to look into that. @rmarkello prepared the tests for Windows if I'm not wrong.

Anyway, my guess is you can figure it out by looking at the azure pipeline.

**Comment by rmarkello** [comment]
:wave: there! 

I did add the Azure pipelines for testing on Windows, yes! I agree with @vinferrer here: WSL is a great option for developers, but I would absolutely encourage keeping Windows testing to ensure that researchers who use Windows can just run `phys2bids` natively (i.e., without having to set up WSL themselves!).

**Comment by eurunuela** [comment]
> :wave: there! 
> 
> 
> 
> I did add the Azure pipelines for testing on Windows, yes! I agree with @vinferrer here: WSL is a great option for developers, but I would absolutely encourage keeping Windows testing to ensure that researchers who use Windows can just run `phys2bids` natively (i.e., without having to set up WSL themselves!).

The idea is to move the windows testing to CircleCI so we do all our testing there. We wouldn't use your azure pipeline account either, so win-win.

**Comment by eurunuela** [comment]
> Which leads me to the question, how do you do the test in windows @eurunuela ?

You could try following these steps (they're taken from the Azure pipeline).

![Screen Shot 2020-10-16 at 10 12 06 AM](https://user-images.githubusercontent.com/13706448/96231824-1bc0d500-0f98-11eb-9522-b7d73160b4bd.png)

**Comment by vinferrer** [comment]
I have check the script, however i do not understand how it is downloading phys2bids, although i suposse it is alreadly in pip, this version of the installation seems to install from the repo

**Comment by smoia** [comment]
Maybe considering [this file](https://github.com/physiopy/phys2bids/blob/master/azure-pipelines.yml), [this file](https://github.com/physiopy/phys2bids/blob/master/.azure-pipelines/windows.yml), and [the logs](https://dev.azure.com/physiopy/phys2bids/_build/results?buildId=565&view=logs&j=2c855bde-037d-57e7-f7a3-61fc65066dac&t=671556eb-5e24-5ed7-3cee-fd6769c5790e), helps. It seems that Azure clones the repo before the steps in the latter file. Still, how that happens is not _totally_ clear to me either.

**Comment by vinferrer** [comment]
I have managed to install phys2bids in windows 10 with pip, I think we can just put this installation, It will be much easier for the normal user

**Comment by vinferrer** [comment]
I may open a PR for this at somepoint

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.2.4`](https://github.com/physiopy/phys2bids/releases/tag/2.2.4) :rocket:

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.3.0`](https://github.com/physiopy/phys2bids/releases/tag/2.3.0) :rocket:
