### ISSUE TITLE
Brainhack Donostia and Global 2020

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#325]
It's Brainhack season again!
From November 9th to November 13th [Brainhack Donostia](https://brainhack-donostia.github.io/) will take place, while between November 30th and December 13th more sites will join the Brainhack global.

We can present projects (that will need a leader) to these events. Any suggestion/volunteer?

**Comment by smoia** [comment]
The Basque contributors are all members of the organising team of Brainhack Donostia, so we will be there. I was already thinking about proposing a project or two (or three or four or five or ..), but I'd like to hear from you what you think we could propose and where, also because being part of the organising committee means we won't be able to dedicate all of our attention to these projects, so we'll need other leaders.

Personally, during the BHD I'll try to catch up with what I didn't do yet here, (re-)start the development of `phys2denoise`, and if I have time and energy, take care of some unfinished business elsewhere (`tedana`).

If anyone wants to take advantage of the Brainhacks for some work on documentation or code development (especially closing the open PRs here to meet abstract submission deadlines), raise your hand!

**Comment by eurunuela** [comment]
I think updating the documentation is a big necessity right now, so that could be a project.

I'd like to point out that submitting the projects by November 4th will make them more visible, as they'll be taken into account by the Brainmatch algorithm we're working on. This algorithm will show every attendee their top 3 matching projects. This means we could potentially get new contributors!!! The submission guidelines are [here](https://brainhack-donostia.github.io/submission/).

I'm pinging @physiopy/all to make sure everyone is part of the discussion.

**Comment by smoia** [comment]
@physiopy/all, I'm sorry to keep bothering you but if we want to submit a project to the BHD we need to do so before our next dev call.

Some possible ideas we could propose are:
1. phys2denoise: design reconsideration, script of the skeleton, current PR integration
2. phys2denoise: integration of new measures/regressors
3. physiopy: Improve documentation on physiological acquisition and use-cases
4. phys2bids: Software documentation update
5. phys2bids: Good first issues
6. phys2bids: automatic channel classification (ouside of OHBM milestone)
7. phys2bids: integration of SIEMENS data (outside of OHBM milestone)

I don't know whether to propose one single project under the banner of physiopy or up to 3/4 project (phys2denoise, documentation, phys2bids for newbies and phys2bids channel classification).

What do you all think?
I'm most probably going to work and take lead on 1. I know that @62442katieb, @tsalor, @sangfrois, @eurunuela, @vinferrer, and @CesarCaballeroGaudes are registered to the event (knowing that the last three and I are also in the org team, so we might be busy). Anyone else joining (e.g. @kristinazvolanek and Chicagoans)?
Is anyone interested in working on `phys2bids` during BHD? If so, what are you interested in? Would you be up to take the lead on something?

**Comment by eurunuela** [comment]
I would be great if someone could finish #292 . As the chair of this year's event, I will be very busy during the event but I'll still try to help with any physiopy project.

**Comment by sangfrois** [comment]
@smoia thanks again for taking the lead Stefano! PLEASE CONTINUE "BOTHERING" US!

I'm quite busy with advancing my master's thesis and preping the neuromod physiological data. Actually, I think my work could fall in the scope of the 3rd point you mentioned (`physiopy: Improve documentation on physiological acquisition and use-cases`).

I'm building a set of tools to deal with 10 hours of data we've collected from our 6 subjects. I think it would be a good use-case for phys2bids. It could offer a blueprint for those who want to convert massive amount of physiological data to BIDS. My method could also benefit from the input of folks in the community.

Would that make any sense to you guys ? If not, I can help with anything else that is *documentation-related*. For instance, again relating to the 3rd point you mentioned, we could think about writing a section on electrodermal activity acquisition ([here](https://phys2bids.readthedocs.io/en/latest/bestpractice.html))

Also, if you're in for my first idea, I will try and give some more details about what I'd consider useful and appropriate to share  (as neuromod data is yet to be public).

**Comment by eurunuela** [comment]
@sangfrois I think that's great! If not phys2bids related, it could be a Brainhack project on its own!

**Comment by RayStick** [comment]
Hi all, things are pretty busy right now, and I am back in the lab doing some pilot scanning. So I am just about keeping up reviewing PRs now and again (thought I know I am a bit slow with that …)! Brainhack Donostia looks really great but I didn’t sign up because I didn’t think I would have time to lead or be too involved in coding projects. I will remind the rest of the Bright lab about it though :)

**Comment by 62442katieb** [comment]
I agree with @sangfrois, please keep bothering us, @smoia! 

I'm also willing to help with documentation (i.e., 3 and 4, above). I'm not sure I know enough about physio-based denoising to be much help with phys2denoise, but I'm happy to contribute wherever there's a need!

**Comment by smoia** [comment]
Alright!
So, should we open three projects? One can be phys2denoise (me), one documentation (@sangfrois), and @62442katieb, if you don't mind, you could open a phys2bids to follow the good first issues and contribute wherever you want (documentation, phys2denoise, phys2bids, ...), helping in planning phys2denoise, helping with documentation updates, and seing if you want to close some PRs around for other folks (like #292), for instance. I'll try to help and coordinate where it's needed! This would keep different projects for different types of contributions clear. If in the end there is not enough time in the project pitches or project presentation, we can still present one main project with everything inside.
What do you think?

**Comment by sangfrois** [comment]
That sounds like a good plan to me @smoia ! 👍

**Comment by eurunuela** [comment]
> If in the end there is not enough time in the project pitches or project presentation, we can still present one main project with everything inside.

I think there will be time.

**Comment by smoia** [comment]
Ok, let's tag the three of us in each project anyway, so that we can help each other in their completion!

**Comment by eurunuela** [comment]
Please submit the project by Monday!

**Comment by 62442katieb** [comment]
Works for me! I'll go ahead and propose a general phys2bids upkeep/documentation project later today.

**Comment by smoia** [comment]
How is the submission going?

I saw that we opened brainhackorg/global2020#39, brainhackorg/global2020#40, and brainhackorg/global2020#46.

Let's check that there is everything and the projects are not overlapping!

We can also add a picture to the issue first message to have it displayed in the website. phys2bids has its own image [here](https://github.com/physiopy/phys2bids/blob/master/docs/_static/phys2bids_card.jpg), we just need to check that it works with the website (or we need to create a new one and adapt it).

@sangfrois, why don't you also add a section about skin conductance for the document in the project?

@62442katieb, I thought I could help reshape your issue, but I don't have permissions. Maybe we can tailor it a bit more around the GFIs and whatnot in phys2bids?

Thank you both for the help! It's great to see such involvement in the community!

**Comment by smoia** [comment]
@sangfrois @62442katieb [here](https://slides.com/ephraim24/physiopy-open-development-solutions-for-physiology-in-mri-e8a4a1)'s the presentation I used during the OHBM hackathon (proposal and wrap up). If you want to have a look at it, the one I'm going to prepare for Monday is going to be very similar.

BTW, are you going to present on Monday? I know 8 AM might be a bit early...

**Comment by sangfrois** [comment]
Cool, thanks for sharing your slides, I'll surely have a look at them.

I guess it wouldn't have been a problem for the early morning presentation. Though, I'm busy scanning for neuromod in that time slot. I'll be able to join in, but won't be able to interact.

**Comment by 62442katieb** [comment]
Yes, thanks for sharing the slides! I will be able to present on Monday (with the help of a sizeable mug of coffee), so I'll whip up a similar slide deck and share.

**Comment by smoia** [comment]
I updated the slides for this event - @62442katieb I was thinking that maybe I can present phys2denoise first, then pass the line to you for phys2bids, then take it back to explain what @sangfrois is going to do! Does it make sense?
If you guys have slides already/ready, let me know!

**Comment by sangfrois** [comment]
[HERE ARE MY SLIDES](https://docs.google.com/presentation/d/1nEmUgnB1e0I0I-szQIJ4VQjFrROn9hfhMfJ-mBzGLjA/edit?usp=sharing), thanks for the reminder, Stefano!

Hope everything looks fine to you !

**Comment by 62442katieb** [comment]
[Here are my slides!](https://docs.google.com/presentation/d/1zlgwpQ3tskJQYyiC9uEw0FX146I6acp38SWiqGZ9n0M/edit?usp=sharing) Did you want to do a mega presentation of the three projects under the physiopy umbrella or as three separate presentations in a row? Either way, my slides probably have a good bit of overlap with what you've got.

**Comment by smoia** [comment]
Ok, thank you guys!
@62442katieb the idea is to make three separate presentations, but one after the other. I'll integrate @sangfrois

**Comment by vinferrer** [comment]
Should we close this issue?

**Comment by smoia** [comment]
BHG season's over (:cry:). Closing the issue too!
