### ISSUE TITLE
Rename utils.writefile() to utils.write_file()

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2bids#332]
## Summary

Most of the functions in `phys2bids.utils` are in PEP8-compatible snake case, but [`phys2bids.utils.writefile()`](https://github.com/physiopy/phys2bids/blob/da3a5306a91a046f3956f1d033b6f86b5c14611b/phys2bids/utils.py#L212) is not. We can rename it to `write_file()` to match convention.

## Next Steps

    * Rename the function
    * Update tests
    * Update all uses of the function throughout the package
    * Update the API page of the docs

**Comment by eurunuela** [comment]
Thank you @tsalo ! I think this can be a good issue for Brainhack Donostia.

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.3.0`](https://github.com/physiopy/phys2bids/releases/tag/2.3.0) :rocket:
