### ISSUE TITLE
Replace utils.path_exists_or_make_it() with os.makedirs()

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2bids#334]
## Summary

The function [`phys2bids.utils.path_exists_or_make_it()`](https://github.com/physiopy/phys2bids/blob/da3a5306a91a046f3956f1d033b6f86b5c14611b/phys2bids/utils.py#L113) can be replaced with [`os.makedirs(exist_ok=True)`](https://docs.python.org/3/library/os.html#os.makedirs). It also doesn't require the `if` statement that's used to check if the path already exists.

## Next Steps

    * Remove the function and associated tests
    * Remove the item from the API docs page
    * Replace the function call throughout the package

**Comment by tsalo** [comment]
Alternatively, we could invest fully in `pathlib` and use that instead, I think.

**Comment by merelvdthiel** [comment]
Hey, I would like to make this my first GFI, would that be ok?

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.3.0`](https://github.com/physiopy/phys2bids/releases/tag/2.3.0) :rocket:
