### ISSUE TITLE
Replace utils.check_input_dir() with os.path.abspath() or pathlib Path object

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2bids#335]
## Summary

The function [`utils.check_input_dir()`](https://github.com/physiopy/phys2bids/blob/da3a5306a91a046f3956f1d033b6f86b5c14611b/phys2bids/utils.py#L14), which removes trailing `/` characters from paths, could be replaced either with `os.path.abspath()` (or a similar `os.path` function) or by using `pathlib` for paths (in which case, handling of trailing characters and the like is done under the hood).

## Next Steps

    * Remove the function and associated tests
    * Remove the item from the API docs page
    * Replace the function call throughout the package

**Comment by 62442katieb** [comment]
I'm on it!
