### ISSUE TITLE
Replace utils.move_file() with shutil.move()

### ISSUE THREAD

**Issue by tsalo** [physiopy/phys2bids#336]
## Summary

I think that the function [`utils.move_file()`](https://github.com/physiopy/phys2bids/blob/da3a5306a91a046f3956f1d033b6f86b5c14611b/phys2bids/utils.py#L152) could be replaced with `shutil.move()`, which automatically overwrites existing files, as desired in `utils.move_file()`.

## Next Steps

    * Remove the function and associated tests
    * Remove the item from the API docs page
    * Replace the function call throughout the package

**Comment by jiyoungsin** [comment]
hey would it be cool if i gave this a shot?

**Comment by jiyoungsin** [comment]
[https://github.com/physiopy/phys2bids/pull/337](https://github.com/physiopy/phys2bids/pull/337)

**Comment by eurunuela** [comment]
> hey would it be cool if i gave this a shot?

Of course!

Actually, I see we don't use the function anywhere but its own unit test. Shall we just remove the function and unit test? @physiopy/phys2bids

**Comment by jiyoungsin** [comment]
Hey @smoia thanks for the assign, however, I am currently working on another project. Would it be cool if @eurunuela got the role?

**Comment by smoia** [comment]
Hey @jiyoungsin !
I saw that you already have an open PR in review for this issue. That's why I assigned it, nothing major. Check the PR out!

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.3.0`](https://github.com/physiopy/phys2bids/releases/tag/2.3.0) :rocket:
