### ISSUE TITLE
Add test to pass a BIDS validator

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#355]
## Detailed Description

I run a BIDS validator on a dataset that I BIDSified with an older version of phys2bids. Fun fact, after a while that the validator worked out fine, now it returns an error on the (old) way to express frequencies.
I realised that we are not testing whether we make output BIDS compatible or not - I know we are, but it is risky. We should check it AT LEAST on one output.
We can use this [BIDS validator](https://github.com/bids-standard/bids-validator) and build a test that we run with the others.

Question for @vinferrer (cause I think you worked on it during HBMH2020 and you recently worked on I/O): do we always transform the sampling frequency into Hz? 

## Context / Motivation

Just to be sure that what we output when we want a BIDS format is 100% BIDS compatible.
Besides, if there's any change in the BIDS spec about physiological files, we need to know it and update phys2bids! 

## Possible Implementation

- Check [this repo](https://github.com/bids-standard/bids-validator) and its docker implementation
- Build a test for CircleCI or a GitHub action that, either cloning the repo or building the docker, runs phys2bids with heuristic rules on a test file and then runs the validator on the output.
- PS: It might not be python based?
- PPS: We need to understand how to return an error when we don't pass the validator
- PPPS: We might have to implement a lot of "ignore errors" and "ignore warnings" to actually pass the test
- PPPPS (and last): maybe some friends from the BIDS team and/or the BIDS validator team can help us setting this up.

**Comment by vinferrer** [comment]
In my txt functions yes we always transform the frequency to Hz

**Comment by vinferrer** [comment]
io.py [#L117-L158](https://github.com/vinferrer/phys2bids/blob/io_txt/phys2bids/io.py#L117-L158)

**Comment by vinferrer** [comment]
They seem to have a BIDS-validator library for python

**Comment by vinferrer** [comment]
I think that the docker solution is the easiest one probably.

**Comment by vinferrer** [comment]
Do you think we need a docker account?
https://circleci.com/docs/2.0/building-docker-images/
