### ISSUE TITLE
Q: is there a phys2bids overview slide to (re)use?

### ISSUE THREAD

**Issue by yarikoptic** [physiopy/phys2bids#361]
I would like to introduce audience to phys2bids in an upcoming webinar, and thought to add some informational slide.  So decided to ask: if there some "ultimate" figure/slide to highlight what phys2bids for and its features in one figure/slide?

if not, that is ok, webshot of https://phys2bids.readthedocs.io/en/latest/ I think is already quite good ;)

**Comment by smoia** [comment]
Hey @yarikoptic!
We don't have one yet, but we might come up with something. When is the webinar?

Tagging @62442katieb and @RayStick to start with and see if we have something somewhere.

BTW: Thank you very, very much for the exposure. I hope we'll get new contributors!

**Comment by smoia** [comment]
Oh, and @danalclop !

**Comment by RayStick** [comment]
I can't think of something like that existing. I think we only have the OHBM related files that I dropped in Issue #341

**Comment by RayStick** [comment]
So the [readthedocs]( https://phys2bids.readthedocs.io/en/latest/ ) page might be best for now :)

**Comment by yarikoptic** [comment]
@RayStick THANK YOU for the OHBM poster PDF - it is very nice and informative.  Silly me should have just searched on https://datalad-datasets.github.io/ohbm2020-posters/#/ ;)  I will take RTD screenshot and add URLs to docs and the poster.

@smoia exposure -- the least I could do!  contributors -- cannot guarantee, but may be at least some ~~whiners~~ test/interested users like yours truly would emerge ;)  

At some point I should also look inside and see may be (ab)use phys2bids to sync our "video capture" @andycon is working on (https://github.com/ReproNim/reprostim/) to BIDS -- purpose is the same, and thus logic for deducing to which bids file to "attach" the recorded extra data should be the same.  Although not "phys" per se, and should be relatively trivial to implement based on time information we capture in `_scans.tsv` files, I do not see why not to just reuse what you probably already have and centralize effort on that.

**Comment by smoia** [comment]
@yarikoptic (some) whiners are always appreciated.
Yes, I remember we were discussing about such an implementation last year in DC. I think that once #219 is merged, working on videos should become quite easy. We can discuss an implementation and join forces on this!

In any case, there's also some showcase of the report @62442katieb and @eurunuela are putting together that might be visually appealing.

**Comment by eurunuela** [comment]
As @smoia said, the report can be great for showcasing. It's currently on [PR #243](https://github.com/physiopy/phys2bids/pull/243) waiting for a fix on Windows machines. Anyway, you can see the report generated by the tests [here](https://1489-208861898-gh.circle-artifacts.com/0/tmp/src/phys2bids/phys2bids/reporting/phys2bids_report.html).

I hope that helps! And thank you for introducing us to the audience! :)

**Comment by smoia** [comment]
Hey @yarikoptic ! Can we close this issue?

**Comment by yarikoptic** [comment]
Oh sure!

**Comment by yarikoptic** [comment]
Thank you
