### ISSUE TITLE
phys2bids December developer call (10.12.2020 @ 15.30 UTC)

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#367]
The call will take place over **Skype** [here](https://join.skype.com/Rm4B7R30TG6g).

Find the agenda [here](https://docs.google.com/document/d/1AJ-APSII_OT588SvYeJSeYRPA1nFfVQZ2uEUgXIcioU/edit?usp=sharing) and don't be scared to add/suggest/press for topics! 

Old minutes are [here](https://drive.google.com/open?id=1zfc-hgRcU1k2XdqKD8v6TGwQX_jeCUea)

Contributors old and new, please join!

**Comment by RayStick** [comment]
I'll join today, but have to leave at 10 past the hour.
