### ISSUE TITLE
Circle CI Credits

### ISSUE THREAD

**Issue by vinferrer** [physiopy/phys2bids#373]
As you may have notice last week we used all the free credits in our Circle CI plan, and this wee we are on the same track with much less PRs:
![image](https://user-images.githubusercontent.com/38909338/102217372-c728d000-3edc-11eb-918f-767ad0b4c63f.png)

This sudden change is due mainly because we started using the windows build in Circle ci for the windows testing. Here you have some info on how many credits/min a job costs:
![image](https://user-images.githubusercontent.com/38909338/102217623-238bef80-3edd-11eb-99c6-4883ffe7ba44.png)

Yes 40 credits/min for windows VM. So there would be two options to discuss

## Outstanding questions

    - Return to azure Pipelines
    - Apply for circle CI open source credits program: https://circleci.com/open-source/  400.000 credits per month

I would go for the second option to see if the open source credits are valid for Windows builds, if they are not, since we are increasing our jobs for different python versions test it would be still nice to have free credits. 
According to the wiki:
```
Open source credit usage
Organizations on our free plan get 400,000 free credits per month for Linux open source builds. Using our free plan and keeping your repository public will enable this for you.

If you build on macOS, we also offer organizations on our free plan 25,000 free credits per month to use on macOS open source builds. For access to this, contact our team at billing@circleci.com.
```
Maybe they are gonna do the same for windows instead of Mac, I think it's worth and email

**Comment by tsalo** [comment]
@vinferrer thank you for looking into this. I agree with you- it sounds like getting free credits would be preferable, so I think we should look into that before switching back to Azure.

**Comment by eurunuela** [comment]
I agree with both of you. Do you want to take the lead on this @vinferrer ?

**Comment by vinferrer** [comment]
Actually since @smoia  has his account linked to the physiopy repo, he should send the email, but I can make a draft

**Comment by vinferrer** [comment]
​​​​​Dear Circle CI Billing Team,

My name is Stefano Moia, one of the colaborators of physiopy (https://github.com/physiopy). We are an open source collaborative project focused on operate physiological files in MRI setups. We started using your CI platform this year and we would like to continue to do so. I understand we already have the 400.000 open source credits for linux since our repository is public. However since our platform is starting to grow (we are opening new projects)  and we would like to incorporate windows tests to our CI pipelines we wanted to ask if there is an option to include free credits for windows VM jobs.

Yours sincerely,

**Comment by vinferrer** [comment]
Feel free to edit

**Comment by vinferrer** [comment]
We could go for an alternative called cirrus CI https://cirrus-ci.org/. Supports Windows and linux  and there isn't credit limits for open source projects. Though I would need help with the migration specially for the codecov part

**Comment by eurunuela** [comment]
Could you please open a PR @vinferrer ? I'll be happy to help but first I'd like to see how big of a change it would be.
