### ISSUE TITLE
OHBM 2021 abstract(s) submission

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#380]
Apologies for the incredible delay I write this issue with.

OHBM abstract submission deadline is close, and it would be great to submit _at least_ one abstract about `physiopy`.
Even better, we could submit two abstracts, one for `phys2bids` and one for `phys2denoise`.
In that case, I think I could take care of one, I can pay for both, and we can adapt the ISMRM submission!

What do you think, @physiopy/all ?

Related to physiopy/phys2denoise#25

**Comment by 62442katieb** [comment]
I'm happy to adapt the ISMRM abstract for the OHBM phys2bids abstract.

**Comment by RayStick** [comment]
I am afraid I am swamped with other work this week, but I can do a final proof read.

**Comment by sangfrois** [comment]
@62442katieb I had fun re-interpreting your first gists on the ISMRM abstract. Do you think ?

@smoia I would feel more comfortable summing up the efforts of physiopy community as a whole. Do you still think it's a good idea or should we really aim for two abstracts ? 

I too already have a submission to deal with, plus the deadline for my PhD application is also feb 1st. So I'll go over our previous abstract and do what I can :)

**Comment by 62442katieb** [comment]
@sangfrois if you've got the bandwidth, go for it!

**Comment by sangfrois** [comment]
Here's a [first draft](https://docs.google.com/document/d/16_pt3YZUrvmcaXnuJXErj3Cvd6DUfIGf5rYIaTgki5A/edit?usp=sharing) 👍

**Comment by smoia** [comment]
Thank you @sangfrois ! I have a quick comment and then a longer discussion to introduce.

Quick comment: OHBM accepts only 2 figures. Given that the contributors should be one, I would merge 2, 3, and 4 into the second figure and go with that.

Longer discussion: For me, this is a very nice presentation of physiopy as a whole, that would be great for the physiopy website (physiopy/physiopy.github.io), where the target is non-specific and possibly everyone. However, at OHBM we expect to meet genuinely interested users, especially for phys2bids, and possibly future contributors. For this reason, I would submit a software demo, and I'm not sure this abstract would serve that purpose. Besides, we added so many new cool features in phys2bids that are worth stating (we extended the interface support, we got the multi-run workflow, we became totally independent from other bidsifier, we are preparing full reports, we are preparing a solution to bidsify physio datasets based on a pre-existing BIDS fMRI dataset, ...) and that are not there - and I think it's a pity.

So, proposal: let's save this text for the website, but if you still have bandwidth for the OHBm submission (you and @62442katieb alike), what about preparing a more tailored abstract for phys2bids?

**Comment by sangfrois** [comment]
Right, @smoia I totally agree with your second point. I'll make a second attempt to focus on : 

>  new cool features in phys2bids that are worth stating (we extended the interface support, we got the multi-run workflow, we became totally independent from other bidsifier, we are preparing full reports, we are preparing a solution to bidsify physio datasets based on a pre-existing BIDS fMRI dataset, ...) 

That's the kind of substance I was missing. I tried to tailor the abstract on the one we made for ISMRM, though, it's true that we have a "software demo" angle this time with HBM.

**Comment by smoia** [comment]
Cool! Don't worry about phys2denoise - if I manage to write another abstract during the weekend, great, otherwise we let this slide (or we integrate it in a sentence in this one).

**Comment by smoia** [comment]
You can also have a look at the abstract we wrote for OHBM 2020 (it's in a previous issue labelled "outreach")

**Comment by sangfrois** [comment]
Ok. Let's try again : here's a "second-first draft" based on your recommendations @smoia 

https://docs.google.com/document/d/1u04a0FbpbCMfMpsDZDzfotgA-wkQEuyqFcxizcEve3o/edit?usp=sharing

sorry for last being last minute ; I forgot to send my comment and kept my browser tab opened since yesterday. I think I'm tired
