### ISSUE TITLE
phys2bids not working with chtrig=0

### ISSUE THREAD

**Issue by drombas** [physiopy/phys2bids#389]
While  working on automatic channel detection I came across the following problem.
## Expected Behavior

When chtrig is set to 0 or no value is entered by the user phys2bids should run anyway and try to detect the trigger automatically.
## Actual Behavior

What happens in phys2bids.py:

By default chtrig is set to 0 
![image](https://user-images.githubusercontent.com/50577357/110607719-c4f8a980-818b-11eb-8165-4c632d6e7abc.png)

however in line 195 an exception is raised when chtrig < 1
![image](https://user-images.githubusercontent.com/50577357/110607296-587daa80-818b-11eb-94b6-7ef16d3f01d0.png)

so the workflow crashes
![image](https://user-images.githubusercontent.com/50577357/110607952-0e48f900-818c-11eb-93e2-0ad7bb179f4f.png)

## Steps to Reproduce the Problem

    1.run phys2bids without entering chtrig or setting chtrig to 0

## Specifications

    - Python version: 3.9
    - phys2bids version: 2.4.0
    - Platform: Ubuntu 20.04.2 LTS

## Possible solution

I guess this could be easily fixed by removing the chtrig<1 check in line 195

**Comment by smoia** [comment]
(Just set chtrig < 0 in 195 and 196)

**Comment by drombas** [comment]
sure, I will check it and open a PR

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.4.1`](https://github.com/physiopy/phys2bids/releases/tag/2.4.1) :rocket:
