### ISSUE TITLE
Tests failing due to errors while executing flake8

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#39]
I know that @vinferrer is looking at that,

The issue is that all the tests we have in travis fail due to a couple of errors in linter.
The first couple of tests (the linters themselves) are obvious to solve.
@rmarkello any idea on why the other tests fail with errors related to flake8?

**Comment by rmarkello** [comment]
I'm happy to tackle this, but you have two open PRs right now. Do you want to go ahead and merge those first, or should I draft a quick flake8-fix PR to address the linter issues and you can just merge those changes into your PRs?

I've copy-pasted the primary issues from the TravisCI logs below just so everyone is aware what's up:

```
phys2bids/physio_obj.py:8:1: F401 'numpy.shape' imported but unused
phys2bids/utils.py:43:1: W293 blank line contains whitespace
phys2bids/phys2bids.py:148:52: W291 trailing whitespace
phys2bids/phys2bids.py:150:33: F821 undefined name 'trigger'
phys2bids/phys2bids.py:153:23: F821 undefined name 'time'
phys2bids/phys2bids.py:169:35: F821 undefined name 'time'
phys2bids/phys2bids.py:180:16: F821 undefined name 'time'
phys2bids/phys2bids.py:187:32: F821 undefined name 'trigger'
phys2bids/phys2bids.py:193:25: F821 undefined name 'header'
phys2bids/phys2bids.py:200:27: F821 undefined name 'data'
phys2bids/phys2bids.py:200:44: F821 undefined name 'data'
phys2bids/phys2bids.py:203:48: F821 undefined name 'data'
phys2bids/phys2bids.py:209:40: F821 undefined name 'data'
phys2bids/phys2bids.py:210:27: F821 undefined name 'data'
phys2bids/phys2bids.py:210:44: F821 undefined name 'data'
phys2bids/phys2bids.py:212:37: F821 undefined name 'data'
phys2bids/phys2bids.py:213:48: F821 undefined name 'data'
phys2bids/phys2bids.py:217:25: F821 undefined name 'data'
phys2bids/phys2bids.py:219:25: F821 undefined name 'header'
phys2bids/heuristics/heur_ex.py:2:1: F401 'fnmatch' imported but unused
phys2bids/heuristics/heur_ex.py:42:100: E501 line too long (155 > 99 characters)
phys2bids/interfaces/acq.py:15:8: W291 trailing whitespace
phys2bids/interfaces/acq.py:18:1: W293 blank line contains whitespace
phys2bids/interfaces/acq.py:22:20: E231 missing whitespace after ','
phys2bids/interfaces/acq.py:33:23: E999 SyntaxError: invalid syntax
```

**Comment by vinferrer** [comment]
Hi Ros, from which commit are you getting this erros, I see they are all related to linting. Did you get them from the last commit of smoia/phys2bids  or are you in your fork? because if i look at the las commit which is :27a4e126ed1df75c1870a1acc88af0417426ffa6 i don't see that many errors:

```
job 21.1 
 phys2bids/phys2bids.py:284:1: E305 expected 2 blank lines after class or function definition, found 1 
 phys2bids/heuristics/heur_ex.py:2:1: F401 'fnmatch' imported but unused
 phys2bids/heuristics/heur_ex.py:42:100: E501 line too long (155 > 99 characters)
job 21.2
phys2bids/phys2bids.py:284:1: E305 expected 2 blank lines after class or function definition, found 1
phys2bids/heuristics/heur_ex.py:2:1: F401 'fnmatch' imported but unused
phys2bids/heuristics/heur_ex.py:42:100: E501 line too long (155 > 99 characters)
```

**Comment by vinferrer** [comment]
And by the way why are the check_type=test failing if we haven't implemented any test?

**Comment by rmarkello** [comment]
I just grabbed these from @smoia's most recent commit to his PR (#38). It's possible the master branch has fewer errors!

Re `check_type=test` failing: it's exactly *because* we haven't implemented any tests. If we add even a simple test then it should begin passing!

**Comment by vinferrer** [comment]
Oh I see thank you very much for explaining I am new on travis so this is all a bit confusing

**Comment by rmarkello** [comment]
No problems! If you're tackling the `flake8` errors I'd be happy to add a few simple tests so we can get things passing. Everyone likes seeing those :heavy_check_mark: marks! 

Let me know if that sounds good and I'll assign this issue to you and open another issue for myself to add a few basic tests for the `utils.py` module.

**Comment by vinferrer** [comment]
I think we have to wait for stefano to finish these push request. Don't think so?

**Comment by rmarkello** [comment]
We can address the changes, make PRs, merge them into master, and @smoia can update his PRs accordingly (by merging master into his branch). The downside is that he may run into some merge conflicts, but they *should* be relatively manageable.

On the other hand, if @smoia thinks that his PRs are going to be finished quickly we can wait for them! They seemed like relatively large changes that might take a while to complete, though...

@smoia: we await your direction.

**Comment by smoia** [comment]
PR #34  address setup but it's minimal - I don't foresee any integration issue.
PR #38  is massive, but I'm quite positive about the fact that the existing `utils.py` won't be touched by it. I may add a couple of functions in `utils.py` though.

**Comment by eurunuela** [comment]
For what I see, the linting test is working correctly. It is correctly pointing out the problems.

**Comment by eurunuela** [comment]
I think we can close this issue. Feel free to open it again if you think flake8 is not being correctly tested.
