### ISSUE TITLE
Docs won't build

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#397]
## Expected Behavior

The docs should be built with no errors.

## Actual Behavior

We get an error saying the function `add_stylesheet` does not exist.

## Steps to Reproduce the Problem

    1.  `make -C docs html`

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.6.0`](https://github.com/physiopy/phys2bids/releases/tag/2.6.0) :rocket:
