### ISSUE TITLE
Refactor phys2bids.use_heuristic

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#40]
In `phys2bids.py`, [`use_heuristic`](https://github.com/smoia/phys2bids/blob/517442dec3cb453a67473d2878f80b119ad85e44/phys2bids/phys2bids.py#L87) needs a bunch of f-string rewritings, and the initialisation of [`fldr`](https://github.com/smoia/phys2bids/blob/517442dec3cb453a67473d2878f80b119ad85e44/phys2bids/phys2bids.py#L95) should use `os` instead.

**Comment by smoia** [comment]
Does anyone in team USA wants to tackle this Issue? @RayStick @AyyagariA @kristinazvolanek @soichih ? Prefereably for Python beginners - check out [this tutorial on f-strings](https://realpython.com/python-f-strings/)

**Comment by eurunuela** [comment]
Any advances on this @kristinazvolanek @RayStick @AyyagariA? I can take care of it if you want.

**Comment by RayStick** [comment]
I haven't had time to get to make a start on this (I think that's the same for the others as well) so if you are able to that'd be grand.

**Comment by smoia** [comment]
This is not an urgent matter, and I think it's a very easy G1I to start approaching python and our code.
Can I suggest that if another person with less experience wants to tackle it (say, before _February_) we reserve this for them, while @eurunuela you play the hard game? There's no rush whatsoever on this.
