### ISSUE TITLE
OHBM2021 - Poster session

### ISSUE THREAD

**Issue by sangfrois** [physiopy/phys2bids#400]
Hi @physiopy/all 
Our abstract was considered exceptional by the jury !!
![image](https://user-images.githubusercontent.com/38385719/118315763-e8a9da00-b4c3-11eb-8779-87928868fc2a.png)

## OHBM2021 - Poster
Poster sessions at OHBM 2021 are coming fast and I would need your feedback on [the poster I drafted](https://docs.google.com/presentation/d/1ww4W3nKV464FGlmtezy3l-mfPdA8VtIgM1sJ43LTkoo/edit?usp=sharing) for phys2bids.

## Poster video !?!?
After the poster (on slide 1), you will find slides for the video presentation which I plan on //**recording on may 18th**// EDIT : **by may 21st**

**We have to send everything by the 25th**

## Outstanding questions

- Does every contributor figure in the list ? Did everyone get his or her credit ?
- Any comments and edits are welcomed on style and content (just make sure you are in suggestion mode so we don't get confused)
   

Thanks everyone!

**Comment by smoia** [comment]
I just added a couple of comments - sorry for the delay!

**Comment by sangfrois** [comment]
@physiopy/all 

here's a [link to the video](https://drive.google.com/file/d/1sxnAIXTefLUz1H3Yq3LXr7CzjYARARRp/view?usp=sharing) 

it's a draft. I can record another take if you have any comments
