### ISSUE TITLE
Automatic linting with CI with black

### ISSUE THREAD

**Issue by htwangtw** [physiopy/phys2bids#409]
## Detailed Description

At the July dev call, @smoia mentioned wanting to add linting with CI on PRs for #402 

## Context / Motivation

We want a more consistent code style, not loading style issue on the project owner, and minimise barriers (ancillary issues such as complex dev environment setup) for new contributors. Everyone wins if there's a lazy linter built into CI. 

## Possible Implementation

[Lint Action](https://github.com/wearerequired/lint-action) supports such a feature. However, it's unclear regarding known conflicts with isort/flake8.
I found another solution using the [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
This solution is buried at the very end of the guide on market place: 
https://github.com/marketplace/actions/run-black-formatter

I am happy to test out and do a PR. Can also check how to integrate `isort` in the same GitHub action.
Any other style-related stuff you want to add to the GitHub action?

**Comment by smoia** [comment]
Just realised this was closed by #445!
