### ISSUE TITLE
Add support for txt files

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#41]
~With the new code, txt is not supported at the moment.~

EDIT: txt is partially supported.
The possible txt formats are (tick what's covered):
- [x] LabChart, with header
- [x] AcqKnowledge, with header
- [ ] LabChart, without header
- [ ] AcqKnowledge, without header
- [x] LabChart, with header and comment
- [ ] ...

**Comment by eurunuela** [comment]
I believe #54 closed this issue.

**Comment by smoia** [comment]
No, this is a general `.txt` support - #54 addressed #48 .
This issue is still open untill we support different types of .txt

**Comment by eurunuela** [comment]
Oh okay. Perfect!

**Comment by vinferrer** [comment]
Do we have other txt files that are not in labchart format?

**Comment by smoia** [comment]
We do!
Starting from [this one](phys2bids/tests/data/Test_belt_pulse_samefreq.txt).
It's acqknowledge!

**Comment by vinferrer** [comment]
Hey guys so I am starting to work on others ``txt`` formats and refractoring ``txt.py`` so there is a reading function for each txt format, so I am assuming AcqKnowledge files in txt format have to be treated here. Any oposition to this?

**Comment by smoia** [comment]
As we said we'll not cover txt files without header before our first full release, I'm going to open an issue specifically for that and close this one.
