### ISSUE TITLE
OHBM 2022 abstract submission

### ISSUE THREAD

**Issue by drombas** [physiopy/phys2bids#419]
Hi @physiopy/all!, I have finished drafting a first version of the OHBM 2022 abstract.

You can find it [here](https://docs.google.com/document/d/1imklQjZFZ2RPg74oyhdGl5-9CBDGEoV3GSAsvAVExjk/edit?usp=sharing). Feel free to suggest/modify parts that may be improved.

Remember that the deadline is this Thursday 12pm EST (sorry for the tight timeframe).

**Comment by smoia** [comment]
Also @rzlim08, @TomasLenc, and @yarikoptic!

**Comment by yarikoptic** [comment]
thank you @smoia for your generous invitation, but my contribution was so insignificant (winning only over `dependabot-preview` for some reason for the same number of commits of 1) that I do not want to dilute the team of more significant contributors.
