### ISSUE TITLE
Do User Testing on refactored code

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#43]
While #42 deals with unit testing and negative testing, this calls for user testing.

As soon as #38 is merged, we can start trying it out on the acqknowledge testing files that we have at disposal, to see how to improve the code!

The new code works **only** on acq

I guess team Chicago was interested in this?
@RayStick @AyyagariA @kristinazvolanek

**Comment by RayStick** [comment]
Just to check  - wait until Issue 38 is merged before trying out user testing? 

I have followed the steps in the README.md, and everything seems to have worked, but haven't attempted to use the code yet.

**Comment by eurunuela** [comment]
Indeed, testing could not start until #38 was merged. It's been merged today, so you can start testing now!

**Comment by RayStick** [comment]
Which branch - 'restructure'?

**Comment by smoia** [comment]
@RayStick you can use the code from `master` already!
Also, open new issues as you find bugs/improvements to do!

**Comment by eurunuela** [comment]
@RayStick you should always use `master` unless you're trying a new feature that has not been merged yet. I believe the `restructure` branch will be removed eventually given that @smoia already restructured the code.

**Comment by RayStick** [comment]
usage: phys2bids [-h] -in FILENAME [-info] [-indir INDIR] [-outdir OUTDIR]
                 [-heur HEUR_FILE] [-sub SUB] [-ses SES] [-chtrig CHTRIG]
                 [-chsel [CHSEL [CHSEL ...]]] [-ntp NUM_TIMEPOINTS_EXPECTED]
                 [-tr TR] [-thr THR] [-chnames [CH_NAME [CH_NAME ...]]] [-v]

It is not clear to me which inputs are compulsory and which are optional?

**Comment by RayStick** [comment]
These inputs make sense to me: FILENAME, INDIR, OUTDIR, SUB, SES, CHTRIG, TR
NUM_TIMEPOINTS_EXPECTED: how accurate does this need to be?
HEUR_FILE: ?
CHSEL: ?
THR: ?
CH_NAME: ?

**Comment by smoia** [comment]
@RayStick , did you try running phys2bids -h and see the long help?
Quickly,
- NUM_TIMEPOINTS_EXPECTED: as accurate as you want. You can play with it too!
- HEUR_FILE: this is an heuristic file, similar to those inside the folder `heur`, like `heur_acq.py`. You need to create one specific to the files you want to convert.
- CHSEL: subselection of channel to output
- THR: threshold used in conjunction with NUM_TIMEPOINTS_EXPECTED, for the estimation of the number of volumes.
- CH_NAME: a list of names that will be the header of your columns (in the .json file).

**Comment by smoia** [comment]
If you think the long help is not enough detailed, please open an issue about it and think how to change it!

**Comment by RayStick** [comment]
Ooops, I did not see the [-h]
Sorry!

**Comment by RayStick** [comment]
Is this the right place to put problems with _running_ the code? i.e. errors that I don't understand?
I understand that id I have suggestions of things to change, I can make an issue.

**Comment by smoia** [comment]
@RayStick , It's prefereable if you open issues to better monitor the changes needed in the code, however You can use [this](https://docs.google.com/document/d/1XPKg7gBFocbiy58KFT6PWjdQjdxnxFSZL_TbnsQT8g4/edit?usp=sharing) for general notes, if you feel more like it.
You need to ask edit permission though.

**Comment by RayStick** [comment]
With test data (tests/data) I think we need a bit more information provided along with these files, so the user knows the “ground truth” when using these test files. I didn’t know if the output was correct when I ran it with data that wasn’t mine. 

 For example knowing these things may be useful: CHTRIG, NUM_TIMEPOINTS_EXPECTED, TR
What do people think? 
Shall we just make sure this info is in each filename, or list this information in one file in the same folder?

Relevant to #9

**Comment by smoia** [comment]
@RayStick, now that we added the json files to our testing files, can we close this issue?

**Comment by eurunuela** [comment]
I think we can close this now that we have integration tests.

**Comment by RayStick** [comment]
@smoia - yes I think we can close this now. Not all the OSF files have json files, but the main testing files do, so I'd say that is sufficient.
