### ISSUE TITLE
phys2bids hanging (or taking more than 2 days to parse 1 file?)

### ISSUE THREAD

**Issue by dangom** [physiopy/phys2bids#431]
## Summary

First time running phys2bids. Even with the `"-info"` flag, the process runs forever.
Here's how I'm calling it:

```
phys2bids -in task-breathhold_acq-highres_physio.txt  -info -chtrig 5
```

And here is the only output I get, after which phys2bids hangs:

```
phys2bids -in task-breathhold_acq-highres_physio.txt  -info -chtrig 5
Module `duecredit` not successfully imported due to "No module named 'duecredit'". Package functionality unaffected.
INFO       Currently running phys2bids version 2.6.2
INFO       Input file is task-breathhold_acq-highres_physio.txt
INFO       File extension is .txt
WARNING    If both acq and txt files exist in the path, acq will be selected.
INFO       Reading the file /cluster/osc/data/pilot/experiment-datasets/pilot-04/physio/task-breathhold_acq-highres_physio.txt
INFO       phys2bids detected that your file is in Labchart format
```

Any ideas on what could be going wrong?

## Additional detail

- pip installed 2 days ago
- python 3.9 on a CentOS machine

**Comment by smoia** [comment]
Hey @dangom, that should definitely not happen!

I wonder if it's a phys2bids/python problem, a file format problem, or a file size problem.
Can you try to run phys2bids on [this file](https://osf.io/b3cq2) locally?
It would help to check if it looks similar to the one you are trying to convert.

Would you be able to share (privately) with me your file, or at least describe it a bit more?

In the meantime, I'm going to do some tests locally to understand if I can do something.

**Comment by dangom** [comment]
Hi @smoia,

Thank you for the response. phys2bids works on the file you shared.
Mine is very similar, except it doesn't have the `UnitName, TopValue and BottomValue` entries for some reason. It also has 16 channels written out even though only 4 are meaningful.

What would be the best way to share my file with you?

Regards,
Daniel

**Comment by smoia** [comment]
Does it have the header though?

**Comment by smoia** [comment]
Also - best way would be to send it (either attached, or shared) to `physiopy.community@gmail.com`

**Comment by dangom** [comment]
It does have the header. I'm sending it over there.

**Comment by smoia** [comment]
Ok, I *think* the reason it's taking this long is due to the current multifrequency channel check. I worked on it, and I *think* I improved performance. I also caught a bug we didn't find before, so that's good news.
I'm running some tests on the new version cause it changed quite drastically.

**Comment by smoia** [comment]
Opening a PR now, when it'll be merged, you'll have a new version of phys2bids that won't take forever (in fact, here's your file plot!)
![hangs](https://user-images.githubusercontent.com/35300580/207475254-ecd23785-b7e3-4a2a-98dd-d2d7d679594e.png)

**Comment by dangom** [comment]
Fascinating :)  Indeed only channels 5, 6, 7 and 8 are meaningful, so glad to see it works as expected.
Thank you for your help with this issue!

**Comment by dangom** [comment]
Amazing!
But the `-chsel` flag is unfortunately not working at my end. I get an IndexError when using it.
Here's the traceback:

```
base ❯ phys2bids -in task-breathhold_physio.txt -chtrig 5 -chsel 6 7 8
Module `duecredit` not successfully imported due to "No module named 'duecredit'". Package functionality unaffected.
INFO       Currently running phys2bids version 2.7.1
INFO       Input file is task-breathhold_acq-highres_physio.txt
INFO       File extension is .txt
WARNING    If both acq and txt files exist in the path, acq will be selected.
INFO       Reading the file /autofs/cluster/osc/data/pilot/experiment-datasets/pilot/physio/task-breathhold_physio.txt
INFO       phys2bids detected that your file is in Labchart format
INFO       Checking if frequencies are different across channels
INFO       Trigger channel name is not in our trigger channel name alias list. Please make sure you choose the proper channel.
INFO       Checking that units of measure are BIDS compatible
INFO       Reading infos
INFO
------------------------------------------------
File task-breathhold_physio.txt contains:
01. Channel 1; sampled at 1000.0 Hz
02. Channel 2; sampled at 1000.0 Hz
03. Channel 3; sampled at 1000.0 Hz
04. Channel 4; sampled at 1000.0 Hz
05. Channel 5; sampled at 1000.0 Hz
06. Channel 6; sampled at 1000.0 Hz
07. Channel 7; sampled at 1000.0 Hz
08. Channel 8; sampled at 1000.0 Hz
09. Channel 9; sampled at 1000.0 Hz
10. Channel 10; sampled at 1000.0 Hz
11. Channel 11; sampled at 1000.0 Hz
12. Channel 12; sampled at 1000.0 Hz
13. Channel 13; sampled at 1000.0 Hz
14. Channel 14; sampled at 1000.0 Hz
15. Channel 15; sampled at 1000.0 Hz
16. Channel 16; sampled at 1000.0 Hz
------------------------------------------------

INFO       saving channel plot to /cluster/osc/data/pilot/experiment-datasets/pilot/physio/code/conversion/task-breathhold_physio.png
INFO       Dropping unselected channels
WARNING    Removing trigger channel - are you sure you are doingthe right thing?
WARNING    Removing trigger channel - are you sure you are doingthe right thing?
WARNING    Skipping trigger pulse count. If you want to run it, call phys2bids using both "-ntp" and "-tr" arguments
INFO       Preparing 1 output files.
Traceback (most recent call last):
  File "/cluster/osc/users/dangom/anaconda3/bin/phys2bids", line 8, in <module>
    sys.exit(_main())
  File "/cluster/osc/users/dangom/anaconda3/lib/python3.9/site-packages/phys2bids/phys2bids.py", line 445, in _main
    phys2bids(**vars(options))
  File "/cluster/osc/users/dangom/anaconda3/lib/python3.9/site-packages/phys2bids/phys2bids.py", line 384, in phys2bids
    if uniq_freq != phys_in[take].freq[chtrig]:
IndexError: list index out of range
```

**Comment by smoia** [comment]
Actually, I'm (hopefully) fixing it in #433
