### ISSUE TITLE
selecting channels results in incorrect json

### ISSUE THREAD

**Issue by sdwilli123** [physiopy/phys2bids#437]
selecting a subset of channels with the -chselect flag creates the correct .tsv file but the accompanying .json file is incorrect and doesn't have a matching number of channels when given custom names  ('time' overwrites the first name).

## Expected Behavior

selecting 3 channels ( eg. -chselect 1 3 4) and feeding in 3 custom channel labels  (-chnames 'breath' 'pulse' 'triggers' ) would  ideally result in only 3 channel labels in the .json file but it does not 
## Actual Behavior

only 2 of the custom channel labels are showing up in the .json file instead of all 3
   "Columns": [
        "time",
        "breath",
        "pulse"
    ]
e.g.
You can see here that 'time' has been inserted in the .json even though it wasn't specified in the custom channel name list ... not sure where it's coming from 

example command:
phys2bids -in ${fname} -indir ${inp} -outdir ${outp} -heur ${p}/scripts/bidsphysio_heurv2.py -sub 01 -chnames 'Breath' 'Pulse' 'Triggers' -chsel 1 3 4

## Steps to Reproduce the Problem

    1.
    2.
    3.

## Specifications

    - Python version: 
    - phys2bids version:
    - Platform:

**Comment by smoia** [comment]
Hello @sdwilli123, I'm very sorry for the late reply.
Can you give me a bit more information about this bug? Mainly, which kind of file were you processing (acq, txt, mat, ...)? From what source (AcqKnowledge, Labchart, ...)?

**Comment by smoia** [comment]
PR passed the test, please try again with new version!

**Comment by smoia** [comment]
:rocket: Issue was released in [`2.8.1`](https://github.com/physiopy/phys2bids/releases/tag/2.8.1) :rocket:

**Comment by smoia** [comment]
@sdwilli123 did you have the chance to try it out?
