### ISSUE TITLE
README - instructions for package install

### ISSUE THREAD

**Issue by RayStick** [physiopy/phys2bids#74]
It may be obvious to regular python users, but it may help to instruct the user to clone the repo into the location where their python packages are located. For me, I cloned it elsewhere first, and then when I later renamed a directory the path to the package was wrong. So just some extra text in the REAME suggesting the location of where this should go (i.e. for me on a macOS it was **/usr/local/lib/python3.7/site-packages** ). If there is a reason not to put it in site-packages, let me know.

**Comment by vinferrer** [comment]
Hi, there is no reason to put it in the location where the site-packages are, actually this is not recommended at all, like last thing you should do. The dir is irrelevant since is the setup.py scritp the one that manages to put the libraries in the right place when installing, but the repo should be in the home dir, for example

**Comment by RayStick** [comment]
I did wonder whether it was a good idea or not. Can you elaborate on why it is the last thing I should do? I understand I would want to clone the repo to my home dir, for example, if it is development code. However when I run the suggested line 'sudo pip3 install -e' in the README.md file that's fine as long as I do not change _any_ of the paths to this directory. If I do, the phys2bids package does not work. How can I avoid that?

What does the '-e' mean in the **sudo pip3 install -e .** command mean? 
Also, I assumed '.' meant current directory, so I tried to change that to a different location but got an error

**Comment by eurunuela** [comment]
I believe that `-e` is just the _key_ that makes pip understand that you're giving a path as an argument (see https://pip.pypa.io/en/stable/reference/pip_install/).

What do you mean by `pip3 install` works as long as you do not change _any_ of the paths to _this_ directory? I don't think I understand the issue here.

**Comment by RayStick** [comment]
Ah, I understand -e now. 

In terms of location, let me see if I can rephrase (please bear in mind I am relatively new to using python): 

I guess I am just trying to work out the 'best' way to interact with this package/have it set up on my computer. I am most familiar with installing packages with pip3 which appears to put them into my default location of **/usr/local/lib/python3.7/site-packages**. I am wondering why this phys2bids package shouldn't go into this location as well?

**Comment by eurunuela** [comment]
So, pip will usually install a package from a url and into a specific Python packages folder on your computer. 

In our case, we're telling pip to install the package located in the given folder (i.e. the phys2bids project) as a new "system command". 

Note that if you want to use other Python packages you install (e.g. numpy or pandas), you must open a Python terminal or use and IDE. However, we want phys2bids to be used as a native system program (kind of), which means it does not need a Python terminal to run.

I hope it's clear now!

**Comment by smoia** [comment]
Attention @RayStick @eurunuela , `pip install -e path/to/package` is not to define a path per se. It's the _developer_ installation option, which let the user modify the code and run it without having to reinstall it.
One could install a local package as `pip install path/to/package` without any problem, but this would "freeze" the installed version of the code to the moment it gets installed, and no new edit would be passed.
Other thing is `pip install -t path/to/target` option, that lets you install your package in a target folder. `-t` and `-e` can be used together.

@RayStick , the fact that you _have_ the code you downloaded into a different folder is not a problem. If you're a user, you can `pip install downloaded/folder` it and you'll actually find it in your default python lib folder ( `/usr/local/lib/python3.7/site-packages` in your case).
The "developer" install is different.

@rmarkello , correct?

**Comment by smoia** [comment]
Another approach is actually _not to use pip in the first place_, but just call `python setup.py` in the right folder.

**Comment by RayStick** [comment]
Thank you @eurunuela and @smoia. This is becoming much clearer now. I will double check I understand by looking at my set up, but I think I do.

It may be good to consider a "user install" and a "developer install" , and what guidance we may want to give.

**Comment by smoia** [comment]
Best way to go, actually! Thank you!
PS: in a not-so-distant-future, we're going to be distributed with pip. Spoiler alert.

**Comment by rmarkello** [comment]
Hey ! Sorry I missed this conversation yesterday. I agree with pretty much everything that was said, but have a minor addition:

1. We should **not** be recommending `sudo pip3 install -e .` as the primary method of install. It is best practice to *never* use `sudo` when installing Python packages (you can irrevocably screw up your machine if you mess with your system install of Python too much).
2. I absolutely agree with @RayStick's suggestion above that we have different recommendations for users vs developers. I would suggest, as @smoia noted, that users go with `pip install .` and developers go with `pip install -e .`

I have just opened a PR (#94) to address the first point. We can address the second as we update documentation.

**Comment by RayStick** [comment]
Can we close this issue now? As #94 was merged
