### ISSUE TITLE
Error output for files with no header

### ISSUE THREAD

**Issue by RayStick** [physiopy/phys2bids#75]
When testing the code, I inputted a file with no header information by accident. The error message I got was not very clear though, see the[ UserTesting doc ](https://docs.google.com/document/d/1XPKg7gBFocbiy58KFT6PWjdQjdxnxFSZL_TbnsQT8g4/edit#heading=h.bd3sq8fzcbg7)for info.

**Comment by vinferrer** [comment]
I will attent to this matter once #29  is done since is more urgen and i will correct also the linting of txt.py

**Comment by smoia** [comment]
Where are we with this issue?

**Comment by RayStick** [comment]
I think this can be closed now? 
It was just about making sure the error was sensible when the input had no header, which seems to have been implemented now, so that's good. If I input a file without a header:

```
File extension is .txt
Reading the file
Traceback (most recent call last):
  File "/usr/local/bin/phys2bids", line 11, in <module>
    load_entry_point('phys2bids', 'console_scripts', 'phys2bids')()
  File "/usr/local/lib/python3.7/phys2bids/phys2bids/phys2bids.py", line 216, in _main
    phys_in = populate_phys_input(infile, options.chtrig)
  File "/usr/local/lib/python3.7/phys2bids/phys2bids/interfaces/txt.py", line 257, in populate_phys_input
    raise AttributeError('Files without header are not supported yet')
AttributeError: Files without header are not supported yet
```
