### ISSUE TITLE
Contribution guidelines

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#84]
I started re-drafting a contribution guidelines.
Please have a look here:
https://docs.google.com/document/d/1FCk3BPp6UZePSf44NDL_4CQeMV4gvQUfr1wbLU9mlfw/edit?usp=sharing

You might need to ask permission to comment it.
Deadline for this is 14/12.

**Comment by eurunuela** [comment]
As discussed during our last Skype call, we should close this issue and merge the contribution guidelines proposal.
