### ISSUE TITLE
BlueprintOutput.delete_at_index() does not update the number of channels in object

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#88]
Possible solution:

```
def delete_at_index(self, idx):
    self.timeseries = np.delete(self.timeseries, idx, axis=0)
    self.ch_amout -= 1
    del(self.ch_name[idx])
    del(self.units[idx])
```

**Comment by rmarkello** [comment]
I might lean towards having `ch_amount` be a property of the class so that we don't actually need to manually update it in all the methods that modify the # of timeseries. Something like:

```python
@property
def ch_amount(self):
    return len(self.timeseries)
```

**Comment by eurunuela** [comment]
Sounds great. We should also add it to `BlueprintInput` as well.

**Comment by rmarkello** [comment]
For sure! But let's get #76 merged in first :+1:

**Comment by smoia** [comment]
Totally agree! @rmarkello are you taking care of this? Can you assign it accordingly?

**Comment by eurunuela** [comment]
Any updates on this @rmarkello ?
