### ISSUE TITLE
0- vs 1-indexing the `run` keyword in `use_heuristic()`

### ISSUE THREAD

**Issue by rmarkello** [physiopy/phys2bids#89]
In https://github.com/physiopy/phys2bids/pull/76#discussion_r356095934 a brief discussion was started about whether the `run` keyword should be 0- or 1-indexed when users provide a `heuristic` to convert their data to BIDS format. We are currently using a 0-indexing approach; I personally think a 1-indexing approach makes more sense here, but am open to discussion on this point!

@smoia found a relevant portion of the [BIDS spec](https://bids-specification.readthedocs.io/en/stable/02-common-principles.html#participant-names-and-other-labels) that touches on this, but the spec is not prescriptive on this point. I'm happy to hear others thoughts and go about issuing a change if it's decided that's warranted!

**Comment by smoia** [comment]
I see that actually we were talking about two different things.
I thought you were referring to padding - that's the only thing the specs refer to.
I didn't find anything related to 0- or 1- indexing, although most of the examples are 1-indexed.

As we don't support multiple files or multiscan files yet, if we want to implement this we should also think about a way to check that then different calls of phys2bids respect the overall indexing, i.e. if the user adopts a 0-indexing and has <entity>-0 <entity>-1 <entity>-2 we don't overwrite  <entity>-1.
(If it's not clear let me know).

**Comment by smoia** [comment]
@rmarkello let's get back to this issue. Shall we agree on suggesting the user to adopt a 1-indexed run keyword, and remain agnostic about it?

**Comment by rmarkello** [comment]
I am for starting at `run-01` and indexing up from there (i.e., `run-00` should not be allowed), yes!

**Comment by smoia** [comment]
Do you think we need to add something to the code as it is now to accommodate for this decision?

**Comment by rmarkello** [comment]
It looks like there are a few instances in the heuristic files provided with `phys2bids` where `run-00` is used:

https://github.com/physiopy/phys2bids/blob/3dc8c8aee1fe5f41836e1c4b0f76575ad4b88285/phys2bids/heuristics/heur_test_acq.py#L19-L22

https://github.com/physiopy/phys2bids/blob/3dc8c8aee1fe5f41836e1c4b0f76575ad4b88285/phys2bids/heuristics/heur_tutorial.py#L19-L22

These heuristics and all relevant tests / documentation would need to be updated to reflect this decision.

**Comment by smoia** [comment]
That's right - actually, those values are just an example. We can definitely change them without any big impact!
