### ISSUE TITLE
Add testing files

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#9]
In order to be able to test the code (and have people test the code), we would need samples of data that work with the code. I have acquired a two minutes sample, with physiological recordings and the MRI trigger, and saved it in many different formats to be able to integrate them.

Could you guys in Chicago create, acquire or share a mock file with labchart and one with the respiract, that can be released publicly, and save it in different ways (as txt, matlab matrix, with/without header, ...)?
It doesn't have to be long (actually, short is better).

**Comment by kristinazvolanek** [comment]
Hi Stefano,

Attached are two sample files that can be made publicly available and used to test the code. The first is the "EndTidals.txt" file exported from the RespirAct during a CO2 challenge. The second is the first 5000 samples of a physiological recording from LabChart (including CO2, O2, trigger, and pulse). Let me know the best place to put these, if I should change the formatting, and if you need any other types of data/file formats. I tried to upload the Matlab matrix of the LabChart file but GitHub said it doesn't support this file type.

Kristina

[Respiract_EndTidals_Header.txt](https://github.com/smoia/phys2bids/files/3769930/Respiract_EndTidals_Header.txt)

[LabChart_Text_NoHeader.txt](https://github.com/smoia/phys2bids/files/3769931/LabChart_Text_NoHeader.txt)

**Comment by smoia** [comment]
@kristinazvolanek , thank you!
Can you create a PR with them in the `/Test` folder? Maybe @RayStick can help you in the process?
The issue might not be the type of file but either the way you tried to upload them or their size (max. 100MB for file in GitHub).
It would be great if you could upload different "flavours" of the same LabChart file as well, like:
- [] A txt with header
- [] A txt with no header
- [] A matlab file
- [] Any other type of file you guys think would be interesting to support!

PS: If it's your first PR you should find a gong and loudly hit it to celebrate it!
Sharing a deep dish ~pizza~ pie is good too!

**Comment by RayStick** [comment]
Apologies for not replying to this …
This past month have been very chaotic and busy (for myself and Kristina!)
I assume we will discuss in the call tomorrow? If there is anything helpful I can do beforehand, let me know (I have some time today).
BW,
Rachael

**Comment by eurunuela** [comment]
How are we doing with this? I believe we are missing a MATLAB file to close this issue.

**Comment by AyyagariA** [comment]
We forgot to create and send the matlab files. I can do that soon! Just to confirm, I'll read in the text file into matlab and save it as a ".mat" file. Is that what you guys are looking for? Thanks!

**Comment by smoia** [comment]
@AyyagariA , I think LabChart can export a file in `.mat` format - correct me if I'm wrong though.

That's what we would be looking for.

Actually, would you be able to make a list of possible labchart outputs?

If that's not possible, we can add a new folder with "non-raw formats", where we can place a `.mat` file.

@eurunuela , don't close this issue just yet - we have so many possible file outputs that we need this issue open to collect more testing data. Alternatively, we can open a different issue for each software we're interested in supporting to ollect data from there.

**Comment by eurunuela** [comment]
I was not looking to close the issue. I just wanted to make sure we’re still working on it.

**Comment by AyyagariA** [comment]
@smoia I will make the list of possible outputs and double check whether I can export directly to .mat format today.

**Comment by smoia** [comment]
@AyyagariA Splendid!
Would you mind editing (3) in this issue (where you see the list of outputs)?

**Comment by AyyagariA** [comment]
@smoia Updated the list above! And you CAN export LabChart directly to matlab. Do you want a matlab file for each of the variations of the data we uploaded to OSF a few weeks ago? Or will 1 or 2 matlab files suffice?

**Comment by smoia** [comment]
@AyyagariA , splendid! Sometimes I remember incredibly random facts.
As for what we need, we need as much as you think is enough for us to have all the different flavours we should be able to deal with!
So, feel free to add up to 42 different files if necessary - as long as they have different characteristics. Better if they are 42 different versions of the same recording!

**Comment by RayStick** [comment]
A quick note that we are now also uploading .json files alongside the test files:
https://phys2bids.readthedocs.io/en/latest/contributorfile.html#testfile

I am going to take my assignment off this issue for now, as I think that @AyyagariA and @kristinazvolanek can manage to upload extra Chicago data files, as and when is needed. However, please do tag me by name if you need my input on that.

**Comment by smoia** [comment]
At what point are we with this issue?
Remember: this is not about supporting things, just about having a file in every output format.
It would be lovely to close it soon!

**Comment by kristinazvolanek** [comment]
I haven't been following the progress on this issue very closely, but there are several different testing files with an associated .json on OSF. If anything specific is missing, I'm happy to try to address that as best as I can remotely. Otherwise, it seems that we could close this issue and re-open in future as more files are needed.

**Comment by smoia** [comment]
> @kristinazvolanek , thank you!
> Can you create a PR putting the files in the `/Test` folder? Maybe @RayStick can help you in the process?
> The issue might not be the type of file but either the way you tried to upload them or their size (max. 100MB for file in GitHub).
> It would be great if you could upload different "flavours" of the same LabChart file as well, like:
> 
>     * [x]  A txt with header
> 
>     * [x]  A txt with no header
> 
>     * [x]  A matlab file
> 
>     * [ ]  Simple Data file
> 
>     * [ ]  Channel Data
> 
>     * [ ]  IGOR
> 
>     * [ ]  WAV file
> 
>     * [ ]  Axon PCLAMP file
> 
>     * [ ]  European Data Format
> 
>     * [ ]  Any other type of file you guys think would be interesting to support!
> 
> 
> PS: If it's your first PR you should find a gong and loudly hit it to celebrate it!
> Sharing a deep dish ~pizza~ pie is good too!

Well, if we could get one version for each of the types in this list for at least two files (one with the same frequency and one multifrequency)

**Comment by kristinazvolanek** [comment]
I don't have access to LabChart on my personal laptop and I believe the easiest way to do this is to export each file type directly from there. @RayStick do you still have LabChart on your computer? If so, would you be able to create these files? I'm happy to help in any way (could add them to the /Test folder and create the PR, etc.) Otherwise, we might have to hold off on this issue until we are able to return to lab.

**Comment by RayStick** [comment]
Ah yes, LabChart software is needed for this. No worries - I can finish this Issue up soon.

**Comment by RayStick** [comment]
I'll put them in OSF, and @kristinazvolanek maybe you can sort putting them in the /Test folder on GitHub via a PR?

**Comment by smoia** [comment]
No need to have them in the GitHub folder!

**Comment by RayStick** [comment]
Ah, but you said earlier - _"Can you create a PR putting the files in the /Test folder?"_

**Comment by smoia** [comment]
Ah, no, sorry for not being clear, I know what happened: a couple of weeks ago I cited a message from October where I was asking to put everything in the test folder. I was actually citing it for the list of files we need. between November and now we decided to put all the files in OSF, I don't remember if that was in a PR discussion or during a dev call.
I think it's alright this way, but if you think it's a good idea to prepare the PR, we can.
Sorry again for the misunderstanding

**Comment by RayStick** [comment]
Ah no worries - I see what happened now. Thanks for clearing it up.
I can just put them in OSF

**Comment by RayStick** [comment]
On OSF, in **lab_chart/chicago/all_exports** I have put _many_ iterations of the same LabChart file. See the 'README' file (in the same folder as the data) for details of each exports. I am only familiar with the txt export of LabChart so can't comment on the appropriate settings for other export formats, and didn't check the data after exporting. I think some of them won't be useful (eg. wav, adidat) but they are there just in case! 

I think we can close this issue now?

**Comment by smoia** [comment]
Yes, we can! Thank you!
