### ISSUE TITLE
[DOC] Adding Code of Conduct to project

### ISSUE THREAD

**Issue by eurunuela** [physiopy/phys2bids#90]
In order to follow the recommended community guidelines (see https://github.com/physiopy/phys2bids/community), we should add a _Code of conduct_ to our project. 

How about we draft it in the following Google Docs?

https://docs.google.com/document/d/1qDdDnuADu87zjxsDEjJpFzGmjETWsK15XQcUlieKCTg/edit?usp=sharing

**Comment by smoia** [comment]
What about slightly modifying the one proposed in the doc in #84 , the [contributor-coventant](https://www.contributor-covenant.org/version/1/4/code-of-conduct.html) ?

(Also, can you give the link to the doc?)

**Comment by eurunuela** [comment]
I'm sorry, I thought the link was already there. I've just edited the first comment.

I like the contributor-covenant but would still like to have some input from everyone. I believe this is an important point in physiopy.

**Comment by eurunuela** [comment]
Maybe we should have an email account (or someone) that can be contacted in case irregular conduct is to be reported.

**Comment by smoia** [comment]
Normally, that's the project manager. Do we want a different figure just for that, or is the project manager ok?

**Comment by eurunuela** [comment]
Project Manager sounds good to me, but maybe we should discuss this with the whole group. What do you think?

**Comment by smoia** [comment]
If this whole issue is not for OHBM, we can talk about it in the first call. No rush on this.

**Comment by eurunuela** [comment]
I think it should be for OHBM itself but not for the submission.

**Comment by eurunuela** [comment]
FYI: I've just created a draft PR to close this issue.

**Comment by eurunuela** [comment]
PR #132 is ready for review.
