### ISSUE TITLE
Correcting linter errors

### ISSUE THREAD

**Issue by smoia** [physiopy/phys2bids#92]
We have a bunch of errors and warnings in the linter test that makes it fail.
While I don't see any problem for Warnings (but maybe I'm wrong), we can't have Errors.
looking at Travis CI details, I see most of them are in `interfaces/txt.py`. @vinferrer , can you check that your scripts pass lintering for Travis CI?

**Comment by vinferrer** [comment]
Yeah I was giving priority to PR #85 but as soon as we are done i will correct this

**Comment by vinferrer** [comment]
linting errors refering to ``interfaces/txt.py`` corrected as part of PR #85, the errors left are from other files

**Comment by eurunuela** [comment]
Could you take care of them @vinferrer and make a PR of all those corrections?

**Comment by eurunuela** [comment]
I believe #85 will close this @vinferrer , right?

**Comment by vinferrer** [comment]
As soon as PR #82 is merged yes, lintin errors are treated there
